---
title: "HBV NA"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(rnaturalearth)
```

```{r}
# make df folder

dir.create("../df/format", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```
```{r}
# make df folder

dir.create("../df/nuc/format", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```


# read files

```{r}
files_long <- list.files("../df/nuc/long", pattern = "nuc") 

files_long
```

```{r}
path_long <- paste0("../df/nuc/long/", files_long)

path_long
```

```{r}
for (i in 1:length(path_long)){
  assign(files_long[i], readRDS(path_long[i]))
}
```


# dem


```{r}
df_nuc_dem_1_long <- df_nuc_dem_1_long %>%
  mutate(AGE = str_replace_all(AGE, "_", "-"))

df_nuc_dem_2_long <- df_nuc_dem_2_long %>%
  mutate(AGE = str_replace_all(AGE, "_", "-"))
```


```{r}
fct_age_1 <- df_nuc_dem_1_long %>% distinct(AGE) %>% pull(AGE)

fct_age_1

length(fct_age_1)
```


```{r}
# check age 39

df_nuc_dem_2_long %>% distinct(AGE) %>% pull(AGE)

```

# format age in dem 3-9
# change "90_94" "95_99" "100_" to "90_" to be consisent with 12 

```{r}
df_nuc_dem_2_long <- df_nuc_dem_2_long %>% 
  mutate(AGE = fct_other(AGE,
                         keep = as.character(fct_age_1[1:18]),
                         other_level = "90-"))
```



```{r}
df_nuc_dem <- df_nuc_dem_1_long %>%
  bind_rows(df_nuc_dem_2_long) %>%
  mutate(AGE = factor(AGE, levels = fct_age_1)) %>%
  mutate(SEX = factor(SEX, levels = c("M", "F"))) %>%
  mutate(across(c(TOTAL), ~ na_if(.x, "-"))) %>%
   mutate(across(c(TOTAL, VALUE, COST_per), ~ as.numeric(.x))) %>%
  mutate(across(c(TOTAL, VALUE), ~ replace_na(.x, 0)))
```

```{r}
df_nuc_dem_2_long %>% filter(TOTAL =="-")
```


```{r}
df_nuc_dem %>% filter(is.na(TOTAL)) %>% View()
```


```{r}
saveRDS(df_nuc_dem, "../df/nuc/format/df_nuc_dem")
```


# prf

```{r}
df_prf <- rnaturalearth::ne_states("japan") %>% 
  as_tibble() %>%
  select(iso_3166_2, name_ja, name_en) %>%
  rename(PRF_jp = "name_ja",
         PRF= "name_en") %>%
  arrange(iso_3166_2)
```

```{r}
df_prf <- df_prf %>%
  mutate(PRF = str_remove(PRF, "Prefecture")) %>%
  mutate(PRF = str_trim(PRF, side = "both")) %>%
  mutate(PRF = str_replace_all(PRF, "Ō", "O")) %>%
  mutate(PRF = str_replace_all(PRF, "ō", "o"))
```


```{r}
df_nuc_prf <- df_nuc_prf_1_long %>%
  bind_rows(df_nuc_prf_2_long) %>%
  mutate(across(c(TOTAL), ~ na_if(.x, "-"))) %>%
   mutate(across(c(TOTAL, VALUE, COST_per), ~ as.numeric(.x))) %>%
  mutate(across(c(TOTAL, VALUE), ~ replace_na(.x, 0))) %>%
  rename(PRF_jp = "PRF")
```


```{r}
df_nuc_prf <- df_nuc_prf %>%
  left_join(df_prf,
            by = join_by(PRF_jp))
```

```{r}
saveRDS(df_nuc_prf, "../df/nuc/format/df_nuc_prf")
```


# end of run

