---
title: "HBV NA"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(cowplot)
library(patchwork)
library(ggtext)
library(scales)
library(ggrepel)

library(fpp3)
library(ggh4x)

library(modifiedmk)

library(broom)
library(DasGuptR)
```

```{r}
# make df folder

dir.create("../df/figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/nuc/analysis", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_nuc_dem <- readRDS("../df/nuc/format/df_nuc_dem")
```

```{r}
df_cost_all <- readRDS("../rds/cost/df_cost_all")
```

```{r}
df_boj <- readRDS("../rds/boj/df_boj")
```


```{r}
df_pop_dem <- readRDS("../rds/pop/dem/df_pop_dem")
```


```{r}
df_nuc_dem <- df_nuc_dem %>%
  rename(YEAR = "YEAR_str")
  
```


# clean dem

```{r}
df_pop_dem <- readRDS("../rds/pop/dem/df_pop_dem")
```

# modify nuc_dem

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "TDF",
                                      "TAF"))) 
```


```{r}
levels_age <- df_nuc_dem %>%
  distinct(AGE, .keep_all = TRUE) %>%
  arrange(AGE) %>%
  pull(AGE)

levels_age 
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(AGE = str_replace_all(AGE, "-", "–")) %>%
  mutate(AGE = factor(AGE, 
                      levels = levels_age %>% str_replace_all( "-", "–")))
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(SEX = case_when(SEX == "M" ~ "Male",
                         SEX == "F" ~ "Female")) %>%
  mutate(SEX = factor(SEX, levels = c("Male", "Female")))
```


# format pop

```{r}
df_pop_dem_cat <- df_pop_dem %>%
  filter(AGE != "total") %>%
  mutate(AGE= str_remove(AGE, "_")) %>%
  mutate(AGE = as.numeric(AGE))
```


```{r}
df_pop_dem_cat <- df_pop_dem_cat %>%
  mutate(AGE_cat = case_when(AGE %in% 0:4 ~ "0-4",
                             AGE %in% 5:9 ~ "5-9",
                             AGE %in% 10:14 ~ "10-14",
                             AGE %in% 15:19 ~ "15-19",
                             AGE %in% 20:24 ~ "20-24",
                             AGE %in% 25:29 ~ "25-29",
                             AGE %in% 30:34 ~ "30-34",
                             AGE %in% 35:39 ~ "35-39",
                             AGE %in% 40:44 ~ "40-44",
                             AGE %in% 45:49 ~ "45-49",
                             AGE %in% 50:54 ~ "50-54",
                             AGE %in% 55:59 ~ "55-59",
                             AGE %in% 60:64 ~ "60-64",
                             AGE %in% 65:69 ~ "65-69",
                             AGE %in% 70:74 ~ "70-74",
                             AGE %in% 75:79 ~ "75-79",
                             AGE %in% 80:84 ~ "80-84",
                             AGE %in% 85:89 ~ "85-89",
                             AGE >= 90 ~ "90-"
                             ))
```

```{r}
df_pop_dem_cat <- df_pop_dem_cat %>%
  mutate(AGE_cat = str_replace_all(AGE_cat, "-", "–")) %>%
  mutate(AGE_cat = factor(AGE_cat, levels = levels_age %>% str_replace_all("-", "–")))
```


# S1
# number of tablets

```{r}
df_nuc_dem %>%
  distinct(DRUG_name, YEAR, SHEET, TOTAL) %>%
  filter(!str_detect(DRUG_name, "エンテカビル"))　%>%
  View()
```

```{r}
df_nuc_dem %>%
  distinct(DRUG_name, YEAR, SHEET, TOTAL) %>%
  filter(!str_detect(DRUG_name, "エンテカビル"))　%>%
  count(YEAR, DRUG_name)
```


```{r}
s1 <- df_nuc_dem %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR, NUC) %>%
  summarise(SUM = sum(TOTAL)/10^6) %>%
  
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "TDF",
                                      "TAF"))) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  ggplot(aes(YEAR, SUM, group = NUC, colour = NUC))+
  geom_line(linewidth = 0.3)+
#  geom_point(size = 1)+
      scale_colour_manual(values = c(
                                   "#9467bd",
                                 "#8c564b",
                                 "#2ca02c",
                                 "#1f77b4",
                               #  "#17becf",
                                 "#bcbd22",
                                 "#d62728"),
                      name = "NA")+
  scale_x_continuous(
                     breaks = c(seq(2014, 2024, 2)),
                     limits = c(2014, 2024)) +
  scale_y_continuous(
                     breaks = c(seq(0, 30, 10)),
                     limits = c(0, 30),
                     label = label_comma()) +
  coord_cartesian(clip = "off")+
    guides(colour = guide_legend(override.aes = list(linewidth = 0.5)))+
  labs(# tag = "A",
       x = "Year",
       y = "Prescription (×10<sup>6</sup> tablets)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(1,1, 1, 1, "mm"))


s1 <- s1 + plot_layout()

ggsave("../figure/FigS1.svg", s1,
       width = 175,
       height = 235/3,
       units = "mm")
```



# each NA


```{r}
df_nuc_dem_etv <- df_nuc_dem %>%
  filter(str_detect(DRUG_name, "バラクルード|エンテカビル")) %>%
  distinct(YEAR, SHEET, DRUG_name, .keep_all = TRUE) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(NUC = "ETV (total)") %>%
  filter(as.numeric(YEAR) >= 2017)

df_nuc_dem_etv
```


```{r}
df_nuc_dem_ind <- df_nuc_dem %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR, NUC) %>%
  summarise(SUM = sum(TOTAL)) %>%
  bind_rows(df_nuc_dem_etv) %>%
  mutate(SUM = case_when( YEAR %in% c("2015", "2019", "2023") ~ SUM/366,
                          .default = SUM/365)) %>%
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "ETV (total)",
                                      "TDF",
                                      "TAF"))) %>%
  mutate(YEAR = as.numeric(YEAR))
```

```{r}
label_nuc_dem_ind <- df_nuc_dem_ind %>%
  filter(YEAR %in% c(2024) |
           (NUC %in% c("ETV (branded)") & YEAR == 2016 ) |
           (NUC %in% c("ETV (total)") & YEAR == 2017 )
           ) %>%
  mutate(label = round(SUM) %>% scales::comma() %>%
           str_trim(side = "both")) %>%
  mutate(hjust = case_when(YEAR == 2024 ~ 0,
                           YEAR == 2017 ~ 0,
                           .default = 0.5)) %>%
  
  mutate(nudge_x = case_when(YEAR == 2024 ~ 0,
                           .default = 0)) %>%
  
  mutate(vjust = case_when(YEAR == 2024 & NUC == "ETV (total)" ~ 0,
                           YEAR == 2024 & NUC == "TAF" ~ 1,
                           YEAR == 2024 & NUC == "LAM" ~ 0,
                           YEAR == 2024 & NUC == "TDF" ~ 1,
                           YEAR %in% c(2016, 2017) ~ 0,
                           .default = 0.5)) %>%
  mutate(y = case_when(YEAR %in% c(2016, 2017) ~ SUM + 90000/50,
                       
                       #YEAR == 2024 & NUC == "ETV" ~ SUM + 90000/50,
                       #YEAR == 2024 & NUC == "TAF" ~ SUM - 90000/50,
                       NUC == "LAM" ~ SUM + 90000/50 *2,
                       #NUC == "TDF" ~ SUM - 90000/50,
                       .default = SUM)) %>%
  mutate(x = YEAR)

label_nuc_dem_ind
```


```{r}
p1_a <- df_nuc_dem_ind %>%
  filter(NUC != "ADF") %>%
  ggplot(aes(YEAR, SUM, group = NUC, colour = NUC)) +
  geom_line(linewidth = 0.3)+
 # geom_point(size = 1)+
  
  scale_colour_manual(values = c(# "#e377c2",
                                 "#9467bd",
                                 "#2ca02c",
                                 "#1f77b4",
                                 "#17becf",
                                 "#bcbd22",
                                 "#d62728"),
                      name = "NA")+
  
  geom_text(data = label_nuc_dem_ind %>% filter(YEAR != "2024"),
            aes(x = x,
                y = y,
                label = label, 
                hjust = hjust,
                vjust = vjust),
            size = 2.8, colour = "black",
            inherit.aes = FALSE)+
  
  geom_text(data = label_nuc_dem_ind %>% filter(YEAR == "2024"),
            aes(x = x,
                y = y,
                label = paste0("  ", label), 
                hjust = hjust,
                vjust = vjust),
            size = 2.8, colour = "black",
            inherit.aes = FALSE)+
  
  
  coord_cartesian(clip = "off")+

  
  scale_x_continuous(
                     breaks = c(seq(2014, 2024, 2)),
                     limits = c(2014, 2024)) +

  scale_y_continuous(
                     breaks = c(seq(0, 90000, 10000)),
                     limits = c(0, 90000),
                     label = label_comma()) +
  
  guides(colour = guide_legend(override.aes = list(linewidth = 0.5)))+
  
  coord_cartesian(clip = "off")+
  labs(tag = "A",
       x = "Year",
       y = "People on NAs (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(1, 1, 1, 1, "mm"))

p1_a
```



# df_nuc_dem_all

```{r}
df_nuc_dem_all <- df_nuc_dem %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR, NUC) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(SUM = case_when( YEAR %in% c(2015, 2019, 2023) ~ SUM/366,
                          .default = SUM/365)) %>%
  filter(NUC != "ADF") %>%
  ungroup() %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(SUM)) %>%
  mutate(NUC = "NUC") %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(index = YEAR, key = NUC)
  

df_nuc_dem_all
```

# adjustment

```{r}
# get 2015

df_pop_dem_cat_long <- df_pop_dem_cat %>%
  group_by(AGE_cat) %>%
  select(YEAR, ALL_total, ALL_m, ALL_f) %>%
  pivot_longer(cols = starts_with("ALL_"),
               names_to = "SEX",
               values_to = "POP")
```

```{r}
df_pop_dem_cat_long <- df_pop_dem_cat_long %>%
  group_by(SEX, AGE_cat, YEAR) %>%
  summarise(POP = sum(POP)) %>%
  
  mutate(SEX = str_remove(SEX, "ALL_")) %>%
  mutate(SEX = str_to_title(SEX)) %>%
  
  mutate(SEX = case_when(SEX == "M" ~ "Male",
                         SEX == "F" ~ "Female",
                         .default = SEX)) %>%
  mutate(SEX = factor(SEX, levels = c("Total", "Male", "Female"))) %>%
  ungroup()
```


# NA

```{r}
# first total from #TOTAL

df_nuc_dem_all <- df_nuc_dem %>%
  filter(NUC != "ADF") %>%
  distinct(DRUG_name, YEAR, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(SUM = case_when( YEAR %in% c(2015, 2019, 2023) ~ SUM/366,
                          .default = SUM/365)) 
```

```{r}
# add pop

df_nuc_dem_all <- df_nuc_dem_all %>%
  left_join(df_pop_dem %>%
              filter(AGE == "total") %>%
              select(ALL_total, YEAR) %>%
              rename(POP = "ALL_total"),
              by = join_by(YEAR))

```

```{r}
df_nuc_dem_all <- df_nuc_dem_all %>%
  mutate(PCT = SUM/(POP*10^3) * 100)
```


```{r}
df_nuc_dem_all_long <- df_nuc_dem_all %>%
  pivot_longer(cols = c(SUM, PCT),
              names_to = "CAT",
              values_to = "SUM"
              ) %>%
  mutate(SEX = "Total")

df_nuc_dem_all_long
```


# by sex and age

```{r}
# overall

df_nuc_dem_adj <- df_nuc_dem %>%
  filter(NUC != "ADF") %>%
  group_by(YEAR, SEX, AGE) %>%
  summarise(SUM = sum(VALUE)) %>%

  ungroup() %>%
  mutate(SUM = case_when( YEAR %in% c(2015, 2019, 2023) ~ SUM/366,
                          .default = SUM/365)) 
  
```


```{r}
# add raw populatio

df_nuc_dem_adj <- df_nuc_dem_adj %>%
  mutate(ID = paste0(YEAR, "_", SEX, "_", AGE)) %>%
  left_join(df_pop_dem_cat_long %>%
              mutate(ID = paste0(YEAR, "_", SEX, "_", AGE_cat)) %>%
              select(ID, POP),
            by = join_by(ID)) %>%
  select(!ID)
  
```

```{r}
# add 2015 population

df_nuc_dem_adj <- df_nuc_dem_adj %>%
  mutate(ID = paste0(SEX, "_", AGE)) %>%
  left_join(df_pop_dem_cat_long %>%
              filter(YEAR == "2015") %>%
              mutate(ID = paste0(SEX, "_", AGE_cat)) %>%
              select(ID, POP) %>%
              rename(POP_2015 = "POP"),
            by = join_by(ID)) %>%
  select(!ID)

```

```{r}
# 2015 age standardisation

df_nuc_dem_adj <- df_nuc_dem_adj %>%
  mutate(SUM_2015 = SUM * POP_2015/POP ) %>%
  mutate(SEX = factor(SEX, levels =c("Male", "Female")))
```



```{r}
df_nuc_dem_adj_long <- df_nuc_dem_adj %>%
  group_by(SEX, YEAR) %>%
  summarise(SUM = sum(SUM),
            SUM_2015 = sum(SUM_2015),
            PCT = sum(SUM)/sum(POP *10^3 / 100)) %>%
  ungroup() %>%
  pivot_longer(cols = c(starts_with("SUM"), PCT) ,
               names_to = "CAT",
               values_to = "SUM")

df_nuc_dem_adj_long 
```

```{r}
df_nuc_dem_long <- df_nuc_dem_all_long %>%
  bind_rows(df_nuc_dem_adj_long) %>%
  mutate(SEX = factor(SEX, levels = c("Total", "Male", "Female"))) %>%
  mutate(LT = case_when(CAT == "SUM_2015" ~ 2,
                        .default = 1)) %>%
  mutate(LT = as.character(LT)) %>%
  mutate(YEAR = as.numeric(YEAR))

df_nuc_dem_long

```


```{r}
df_nuc_dem_long %>%
  mutate(YROW = str_remove(CAT, "_2015")) %>%
  mutate(ID = paste0(SEX, "_", CAT)) %>%
  ggplot(aes(YEAR, SUM, group = ID, linetype = LT))+
  geom_line(linewidth = 0.3)+
  facet_grid2(rows = vars(YROW),
              cols = vars(SEX),
              scales = "free_y")+
  theme_classic()
```

# run mmky

```{r}
mmky_nuc_dem <- df_nuc_dem_long %>%
  filter(CAT != "SUM_2015") %>%
  nest(data = -c(SEX, CAT)) %>%
  mutate(model = purrr::map(data,
                            ~ mmky(.x$SUM)),
    tau = map_dbl(model, "Tau"),
    p_value_old = map_dbl(model, "old P.value"),
    p_value = map_dbl(model, "new P-value"),
    slope = map_dbl(model, "Sen's slope")
  )

mmky_nuc_dem
```

```{r}
get_exp <- function(x){

  if (x > 0.001){
    
    return("")
  }
  
  else {
  
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    ex <- p %>% str_extract("(?<=e).+") %>%
      str_remove_all("(?<=\\-)0+") %>%
      str_replace("-", "−")
    
    return(ex)
  }
}

get_expv <- Vectorize(get_exp)
```

```{r}
get_num <- function(x){

    if (x > 0.001){
    
      p <- formatC(x, digits = 2, format = "fg", flag = "#")
      
      return(p)
  }
  
  else {
  
    p <- formatC(x, digits = 1, format = "e", flag = "#")
    
    num <- p %>% str_extract(".+(?=e)")
    
    num <- str_c(num, "×10")
      
    return(num)
  }
}

get_numv <- Vectorize(get_num)
```

```{r}
label_nuc_dem <- mmky_nuc_dem %>%
  mutate(tau = formatC(tau, digits = 2, format = "fg", flag = "#")) %>%
  mutate(tau = str_replace(tau, "-", "−")) %>%
  
  mutate(p_exp = get_expv(p_value)) %>%
  mutate(p_num = get_numv(p_value)) %>%

  mutate(slope = round(slope)) %>%
  mutate(slope = scales::comma(slope)) %>%
  mutate(slope = str_replace(slope, "-", "−")) %>%
  
  mutate(label_slope = paste0("beta == '", slope, "'" )) %>%
  mutate(label_tau = paste0("tau == '", tau, "'")) %>%
  mutate(label_p = paste0("italic(p) == '", p_num, "'^'", p_exp, "'")) %>%
  
  mutate(xpos = 2018) %>%
  mutate(ylim = case_when(CAT == "SUM" ~ 150*10^3,
                          CAT == "PCT" ~ 0.15)) %>%
  mutate(ytau = ylim * 0.25,
         yp = ylim * 0.1)
  
label_nuc_dem
```

```{r}
anno_nuc_dem <- df_nuc_dem_long %>%
   filter(YEAR %in% c(2014, 2024)) %>%
  filter(CAT != "SUM_2015") %>%
   mutate(hjust = case_when(YEAR == 2014 ~ 0,
                            YEAR == 2024 ~ 1)) %>%
   mutate(vjust =  case_when(YEAR == 2014 ~ 1,
                            YEAR == 2024 ~ 0)) %>%
  mutate(ylim = case_when(CAT == "SUM" ~ 150*10^3,
                          CAT == "PCT" ~ 0.15)) %>%
  
  mutate(ybrk = ylim/3) %>%
  
  mutate(ypos = case_when(YEAR == 2014  ~ SUM - ylim/50,
                         YEAR == 2024  ~ SUM + ylim/50)) %>%
  mutate(label = case_when(CAT == "SUM"  ~ round(SUM) %>% scales::comma(),
                            CAT == "PCT"  ~ formatC(SUM, digits = 3, format = "f", flag = "#"))) %>%
  mutate(ylab = case_when(CAT == "SUM"  ~ "People on NAs (n)",
                          CAT == "PCT"  ~ "Prevalence (%)"
    
  ))

anno_nuc_dem
```

```{r}
levels_id <- paste0( c("Total", rep(c("Male", "Female"), 2)),
                     "_SUM") %>%
  paste0(c(rep("", 3), rep("_2015", 2)))

levels_id
```


```{r}
# plot number

p1_b1 <- df_nuc_dem_long %>%
  filter(str_detect(CAT, "SUM")) %>%
  mutate(YROW = str_remove(CAT, "_2015")) %>%
  
  mutate(ID = paste0(SEX, "_", CAT)) %>%
  mutate(ID = factor(ID, levels = levels_id)) %>%
  
  ggplot(aes(YEAR, SUM, group = ID, colour = ID, linetype = LT))+
  
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = c("#7f7f7f", "#1f77b4", "#d62728",
                               "black", "black"))+
  scale_linetype_manual(values = c(1, 2),
                        name = "Count",
                        labels = c("Raw", "Age-standardised"))+
  
  facet_grid2(rows = vars(YROW),
              cols = vars(SEX),
              remove_labels = "all",
              axes = "all",
              scales = "free_y")+
  
  geom_text(data = label_nuc_dem %>% filter(str_detect(CAT, "SUM")) ,
            aes(x = xpos, y = yp, label = label_p),
            vjust = 0.5, hjust = 0, size = 2.8,
            parse = TRUE,
            inherit.aes = FALSE)+
    
  geom_text(data = label_nuc_dem %>% filter(str_detect(CAT, "SUM")) ,
            aes(x = xpos, y = ytau, label = label_tau),
            vjust = 0.5, hjust = 0, size = 2.8,
            parse = TRUE,
            inherit.aes = FALSE)+
    
  geom_text(data = anno_nuc_dem %>% filter(str_detect(CAT, "SUM")) ,
            aes(x = YEAR, y = ypos, label = label,
                hjust = hjust, vjust = vjust),
            size = 2.8,
            colour = "black",
            inherit.aes = FALSE)+
  
  
  scale_x_continuous(limits = c(2014, 2024),
                     breaks = seq(2014, 2024, 3)) +
  
  scale_y_continuous(limits = c(0, 150000),
                                          breaks = seq(0, 150000, 50000),
                                          labels = scales::label_comma())+
  
  guides(colour = "none",
         linetype = guide_legend(override.aes = list(colour = "black",
                                                     linewidth = 0.5)))+
  labs(tag = "B",
       x = "Year",
       y = "People on NAs (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5, margin = margin(1,0, 1, 0, "mm")),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(1, 1, 1, 1, "mm"))

p1_b1
```

```{r}
# plot number

p1_b2 <- df_nuc_dem_long %>%
  filter(str_detect(CAT, "PCT")) %>%

  ggplot(aes(YEAR, SUM, group = SEX, colour = SEX))+
  
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = c("#7f7f7f", "#1f77b4", "#d62728",
                               "black", "black"))+
  
  facet_grid2(rows = vars(CAT),
              cols = vars(SEX),
              remove_labels = "all",
              axes = "all",
              scales = "free_y")+
  
  geom_text(data = label_nuc_dem %>% filter(str_detect(CAT, "PCT")) ,
            aes(x = xpos, y = yp, label = label_p),
            vjust = 0.5, hjust = 0, size = 2.8,
            parse = TRUE,
            inherit.aes = FALSE)+
    
  geom_text(data = label_nuc_dem %>% filter(str_detect(CAT, "PCT")) ,
            aes(x = xpos, y = ytau, label = label_tau),
            vjust = 0.5, hjust = 0, size = 2.8,
            parse = TRUE,
            inherit.aes = FALSE)+
    
  geom_text(data = anno_nuc_dem %>% filter(str_detect(CAT, "PCT")) ,
            aes(x = YEAR, y = ypos, label = label,
                hjust = hjust, vjust = vjust),
            size = 2.8,
            colour = "black",
            inherit.aes = FALSE)+
  
  
  scale_x_continuous(limits = c(2014, 2024),
                     breaks = seq(2014, 2024, 3)) +
  
  scale_y_continuous(limits = c(0, 0.15),
                     breaks = seq(0, 0.15, 0.05),
                     labels = scales::label_comma())+
  
  guides(colour = "none",
         linetype = guide_legend(override.aes = list(colour = "black",
                                                     linewidth = 0.5)))+
  labs(
       x = "Year",
       y = "Prevalence (%)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.text.y = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5, margin = margin(1,0, 1, 0, "mm")),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(1, 1, 1, 1, "mm"))

p1_b2
```


# decomposition

```{r}
# decomposition all

dg_nuc_dem <- df_nuc_dem_adj %>%
  filter(SEX != "Total") %>%
  filter(YEAR %in% c("2014", "2024")) %>%
  dgnpop(pop = "YEAR",
         factors = "SUM",
         id_vars = c("SEX", "AGE"),
         crossclassified = "POP") |>
  dg_table()

dg_nuc_dem
  
```

```{r}
p1_c <- dg_nuc_dem %>%
  rownames_to_column(var = "ROW") %>%
  mutate(ROW = str_to_title(ROW)) %>%
  mutate(ROW = str_remove(ROW, "_.+")) %>%
  mutate(ROW = str_replace(ROW, "Sum", "Rate")) %>%
  filter(ROW != "Crude") %>%
  mutate(ROW = factor(ROW, levels = c("Age","Sex", "Rate"))) %>%
  mutate(LABEL = formatC(decomp, digits = 2, format = "fg", flag = "#")) %>%
  mutate(LABEL = str_remove(LABEL, "\\.$")) %>%
  mutate(LABEL = str_trim(LABEL, side = "both")) %>%
  mutate(LABEL = paste0(LABEL, "%")) %>%
  ggplot(aes(ROW, decomp, fill = ROW))+
  geom_col(width = 0.5)+
  
  scale_fill_manual(values = c("#2ca02c",
                               "#ff7f0e",
                               "#1f77b4"))+
  
  geom_text(aes(y = decomp + 100/50, label = LABEL),
            vjust = 0, hjust = 0.5, size = 2.8, colour = "black")+
  scale_y_continuous(limits = c(0, 100),
                     breaks = seq(0, 100, 25),
                     expand = c(0, 0))+
  coord_cartesian(clip= "off") +
  labs(tag = "C",
       x = "Factor",
       y = "Contribution (%)")+
    theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        plot.margin = margin(1, 1, 1, 1, "mm"))

p1_c
```



```{r}
df_nuc_dem_adj %>%
  filter(SEX != "Total") %>%
  filter(YEAR %in% c("2014", "2024")) %>%
  filter(str_detect(AGE, "^65|^7|8^|9^")) 
```


```{r}
# decomposition 65 years old

df_nuc_dem_adj %>%
  filter(SEX != "Total") %>%
  filter(YEAR %in% c("2014", "2024")) %>%
  filter(str_detect(AGE, "^65|^7|^8|^9")) %>%
  dgnpop(pop = "YEAR",
         factor = "SUM",
         id_vars = c("SEX", "AGE"),
         crossclassified = "POP") |>
  dg_table()
  
```

```{r}
df_nuc_dem_adj_2 <- df_nuc_dem_adj %>%
      mutate(AGE = fct_recode(AGE,
                          "0–19" = "0–4",
                          "0–19" = "5–9",
                          "0–19" = "10–14",
                          "0–19" = "15–19")) 

levels_age_new <- df_nuc_dem_adj_2 %>%
  arrange(AGE) %>%
  distinct(AGE) %>%
  pull(AGE) %>%
  as.character()

df_nuc_dem_adj_2 <- df_nuc_dem_adj_2 %>%
  mutate(AGE = factor(AGE, levels = levels_age_new))

df_nuc_dem_prop <- df_nuc_dem_adj_2 %>%
  group_by(YEAR, SEX) %>%
  mutate(ALL = sum(SUM)) %>%
  ungroup() %>%
  mutate(PCT = SUM/ALL*100) %>%
  bind_rows(df_nuc_dem_adj_2 %>%
              group_by(YEAR, AGE) %>%
              summarise(SUM = sum(SUM)) %>%
              mutate(SEX = "Total") %>%
              mutate(ALL = sum(SUM)) %>%
              ungroup() %>%
              mutate(PCT = SUM/ALL*100)) %>%
  mutate(SEX = factor(SEX, levels = c("Total", "Male", "Female")))

df_nuc_dem_prop
```



```{r}
p1_d <- df_nuc_dem_prop %>%
    ggplot(aes(AGE, PCT, group = YEAR, colour = YEAR)) +
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = as.vector(pals::kovesi.rainbow(n = 11)),
                      name = "Year")+
  scale_y_continuous(limits = c(0, 25),
                     breaks = seq(0, 25, 5))+
  
  facet_wrap2(vars(SEX),
              axes = "all",
              remove_labels = "all")+
  
  labs(tag = "D",
       x = "Age",
       y = "Proportion (%)")+
  guides(colour = guide_legend(nrow = 2, byrow = TRUE,
                               title.position = "left",
                               override.aes = list(linewidth = 0.5)))+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.background = element_blank(),
      strip.text = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5, margin = margin(1, 0, 1, 0, "mm")),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "bottom",
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        panel.spacing = unit(2, "mm"),
      
        legend.key.height = unit(5, 'mm'),
        legend.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.spacing = unit(2, "mm"),
      
        plot.margin = margin(1,1, 1, 1, "mm"))

p1_d
```

```{r}
p1_a_leg <- p1_a %>% get_legend() %>% ggplotify::as.ggplot()

p1_b1_leg <- p1_b1 %>% get_legend() %>% ggplotify::as.ggplot()
```

```{r}
p1_a_plot <-  p1_a + theme(legend.position = "none")
```

```{r}
p1_b1_plot <- p1_b1 + theme(axis.title.x = element_blank(),
                            axis.text.x = element_blank(),
                            legend.position = "none")

p1_b2_plot <- p1_b2 + theme(strip.text = element_blank())

p1_b1_plot

p1_b2_plot
```

```{r}
p1 <- p1_a_plot + p1_a_leg +
  p1_b1_plot + p1_b1_leg +
  p1_b2_plot + p1_c +
  p1_d +
  plot_layout(design = "
              AAAAAAB#
              AAAAAAB#
              AAAAAAB#
              AAAAAAB#
              CCCCCCD#
              CCCCCCD#
              CCCCCCD#
              EEEEEEFF
              EEEEEEFF
              EEEEEEFF
              GGGGGGGG
              GGGGGGGG
              GGGGGGGG")&
  theme(legend.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.spacing = unit(2, "mm"),
        legend.key.height = unit(4, "mm"))

p1
```

```{r}
ggsave( "../figure/Fig1.pdf",
        p1,
        width = 175,
        height = 235,
        units = "mm")
```

