---
title: "HBV NA"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

library(fpp3)

library(cowplot)
library(patchwork)
library(ggtext)
library(scales)

library(ggh4x)

library(viridis)
library(pals)
```

```{r}
# make df folder

dir.create("../df/figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/nuc/analysis", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_nuc_dem <- readRDS("../df/nuc/format/df_nuc_dem")
```

```{r}
df_cost_all <- readRDS("../rds/cost/df_cost_all")
```

```{r}
df_boj <- readRDS("../rds/boj/df_boj")
```

```{r}
df_pop_dem <- readRDS("../rds/pop/dem/df_pop_dem")
```

# modify nuc_dem

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "TDF",
                                      "TAF"))) %>%
  rename(YEAR = "YEAR_str")
  
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(AGE_ori = AGE) %>%
    mutate(AGE = fct_recode(AGE,
                          "0-19" = "0-4",
                          "0-19" = "5-9",
                          "0-19" = "10-14",
                          "0-19" = "15-19")) 
```

```{r}
levels_age <- df_nuc_dem %>%
  distinct(AGE, .keep_all = TRUE) %>%
  arrange(AGE) %>%
  pull(AGE)

levels_age 
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(AGE = str_replace_all(AGE, "-", "–")) %>%
  mutate(AGE = factor(AGE, 
                      levels = levels_age %>% str_replace_all( "-", "–")))
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(SEX = case_when(SEX == "M" ~ "Male",
                         SEX == "F" ~ "Female")) %>%
  mutate(SEX = factor(SEX, levels = c("Male", "Female")))
```


```{r}
p2 <- df_nuc_dem %>%
   filter(!NUC %in% c("ADF")) %>%
    mutate(NUC = fct_recode(NUC,
                          ETV = "ETV (branded)",
                          ETV = "ETV (generic)")) %>%
  group_by(AGE, SEX, YEAR, NUC) %>%
  summarise(SUM = sum(VALUE)) %>%
  ungroup() %>%
  group_by(SEX, YEAR, AGE) %>%
  mutate(PCT = prop.table(SUM)*100) %>%
  ungroup() %>%
  ggplot(aes(AGE, PCT , fill = NUC))+
  geom_col(width = 0.6)+
  scale_fill_manual(values = c("#9467bd" , 
                               # "#8c564b", 
                               "#17becf", 
                               "#bcbd22", 
                               "#d62728"),
                    name = "NA")+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 100, 50))+
  facet_grid2(rows = vars(YEAR), cols = vars(SEX),
              axes = "all",
              remove_labels = "x",
              )+
  guides(fill = guide_legend(title.position = "left",
                             override.aes = list(size = 2)))+
  labs(y = "Proportion (%)",
       x = "Age")+
  theme_classic()+
  theme(strip.background = element_blank(),
        strip.text.x = element_text(size = 8, colour = "black", face = "bold" ),
        strip.text.y = element_text(size = 8, colour = "black", face = "bold" , angle = 0),
        strip.placement = "outside",
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "bottom",
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        panel.spacing  = unit(3, "mm"),
        legend.key.size = unit(4, 'mm'),
        plot.margin = margin(0,0,0,0, "mm"),
        legend.margin = margin(0,0,0,0, "mm"),
        legend.box.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.spacing = unit(2, "mm"))

p2
```

```{r}
p2 <- p2+plot_layout()#&
  # theme(legend.box.spacing = unit(3, "mm"))

ggsave("../figure/Fig3.pdf",p2,  width = 175, height = 235, units = "mm")
```


