---
title: "HBV NA"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(cowplot)
library(patchwork)
library(ggtext)
library(scales)

library(fpp3)
```

```{r}
# make df folder

dir.create("../df/figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/nuc/analysis", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_nuc_dem <- readRDS("../df/nuc/format/df_nuc_dem")
```

```{r}
df_cost_all <- readRDS("../rds/cost/df_cost_all")
```

```{r}
df_boj <- readRDS("../rds/boj/df_boj")
```


```{r}
df_pop_dem <- readRDS("../rds/pop/dem/df_pop_dem")
```


```{r}
df_nuc_dem <- df_nuc_dem %>%
  rename(YEAR = "YEAR_str")
  
```


# check price

```{r}
df_nuc_dem %>%
  filter(YEAR == "2023") %>%
  filter(str_detect(NUC, "ETV|TDF|TAF")) %>%
  distinct(NUC, COST_per, .keep_all = TRUE) %>%
  select(NUC, COST_per)
```


```{r}
df_nuc_dem %>%
  filter(YEAR == "2023") %>%
  filter(str_detect(NUC, "ETV|TDF|TAF")) %>%
  distinct(NUC, COST_per, YEAR) %>%
  mutate(IRP_year = case_when(str_detect(NUC, "ETV") ~ 36,
                              str_detect(NUC, "TDF") ~ 30,
                              .default = NA)) %>%
  left_join(df_boj %>% select(YEAR, USD_JPY),
            by = join_by(YEAR)) %>%
  mutate(COST_year = COST_per * 365/USD_JPY) %>%
  mutate(MPR = COST_year/IRP_year)
```


```{r}
print(1341.1/36)

print(1554.3/30)
```


# check sheet for each year

```{r}
df_nuc_dem %>%
  distinct(DRUG_name, YEAR, SHEET, .keep_all = TRUE) %>% 
  count(DRUG_name, YEAR) 
```

```{r}
df_nuc_dem %>%
  distinct(DRUG_name, YEAR, COST_per, .keep_all = TRUE) %>% 
  filter(str_detect(DRUG_name, "エンテカビル")) %>%
  mutate(OD = if_else(str_detect(DRUG_name, "ＯＤ"), "OD", "non-OD")) %>%
  distinct(YEAR, OD, COST_per) %>%
  arrange(YEAR, OD)
```


```{r}
df_nuc_dem %>%
  distinct(DRUG_name, YEAR, .keep_all = TRUE) %>% 
  select(YEAR, DRUG_name, NUC, COST_per) %>%
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "TDF",
                                      "TAF"))) %>%
  arrange(NUC, YEAR) %>% View()
```

```{r}
df_nuc_dem %>%
  distinct(NUC, YEAR, COST_per, .keep_all = TRUE) %>% 
  select(YEAR, DRUG_name, NUC, COST_per) %>%
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "TDF",
                                      "TAF"))) %>%
  arrange(NUC, YEAR) %>% View()
```

```{r}
df_nuc_dem %>%
  distinct(DRUG_name, YEAR, SHEET, .keep_all = TRUE) %>% 
  count(DRUG_name, YEAR) %>%
  filter( (!str_detect(DRUG_name, "エンテカビル")) & n < 3)
```


```{r}
df_nuc_dem %>%
  distinct(DRUG_name, YEAR, SHEET, .keep_all = TRUE) %>% 
  filter(str_detect(DRUG_name, "ヘプセラ")　& YEAR == "2022")
```


```{r}
df_nuc_dem_etv <- df_nuc_dem %>%
  filter(str_detect(DRUG_name, "バラクルード|エンテカビル")) %>%
  distinct(YEAR, SHEET, DRUG_name, .keep_all = TRUE) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(NUC = "ETV (total)") %>%
  filter(as.numeric(YEAR) >= 2017)

df_nuc_dem_etv
```

# lets calculate cost


```{r}
df_nuc_dem %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  mutate(COST_total = COST_per * TOTAL) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  mutate(NUC = "Total") %>%
  ggplot(aes(YEAR, SUM, group = NUC))+
  geom_line(linewidth = 0.3)+
  geom_point()+
  scale_y_continuous(
                     breaks = c(seq(0, 40, 10)),
                     limits = c(0, 40),
                     label = label_comma()) +
#  coord_cartesian(clip = "off")+
  labs(tag = "A",
       x = "Year",
       y = "NUC cost (10<sup>9</sup> JPY)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),,
        axis.title = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = unit(c(0,5,0,0), "mm"))
```

```{r}
# convert to USD

df_nuc_dem %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  mutate(COST_total = COST_per * TOTAL) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(COST_total)) %>%
  left_join(df_boj, by = join_by(YEAR)) %>%
  mutate(SUM_usd = SUM/USD_JPY) %>%
  mutate(SUM_usd_m = SUM_usd/ 10^6) %>%
  select(YEAR, SUM_usd_m, SUM)
```

```{r}
df_nuc_dem %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  mutate(COST_total = COST_per * TOTAL) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(COST_total)) %>%
  left_join(df_boj, by = join_by(YEAR)) %>%
  mutate(SUM_usd = SUM/USD_JPY) %>%
  mutate(SUM_usd_m = SUM_usd/ 10^6) %>%
  mutate(NUC = "Total") %>%
  ggplot(aes(YEAR, SUM_usd_m, group = NUC))+
  geom_line(linewidth = 0.3)+
  geom_point()+
  scale_y_continuous(
                     breaks = c(seq(0, 400, 100)),
                     limits = c(0, 400),
                     label = label_comma()) +
#  coord_cartesian(clip = "off")+
  labs(tag = "A",
       x = "Year",
       y = "NUC cost (10<sup>6</sup> USD)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),,
        axis.title = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = unit(c(0,5,0,0), "mm"))
```


```{r}
tsbl_nuc_cost <- df_nuc_dem %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  mutate(COST_total = COST_per * TOTAL) %>%
  group_by(YEAR, NUC) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  
  bind_rows(df_nuc_dem %>%
              filter(str_detect(DRUG_name, "バラクルード|エンテカビル")) %>%
              distinct(YEAR, SHEET, DRUG_name, .keep_all = TRUE) %>%
              mutate(COST_total = COST_per * TOTAL) %>%
              group_by(YEAR) %>%
              summarise(SUM = sum(COST_total)/10^9) %>%
              mutate(NUC = "ETV (total)") %>%
              filter(as.numeric(YEAR) >= 2017)) %>%
  
  bind_rows(df_nuc_dem %>%
              distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
              mutate(COST_total = COST_per * TOTAL) %>%
              group_by(YEAR) %>%
              summarise(SUM = sum(COST_total)/10^9) %>%
              mutate(NUC = "Total")) %>%
  
  mutate(NUC = factor(NUC, levels = c("Total",
                                      "LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "ETV (total)",
                                      "TDF",
                                      "TAF"))) %>%
  ungroup() %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(index = YEAR, key = NUC)
```

```{r}
tsbl_nuc_cost_usd <- tsbl_nuc_cost %>%
  left_join(df_boj %>% mutate(YEAR = as.numeric(YEAR)) %>% select(YEAR, USD_JPY),
            by = join_by(YEAR)) %>%
  mutate(SUM_usd = SUM* 10^9/USD_JPY) %>%
  mutate(SUM_usd_m = SUM_usd/10^6)


tsbl_nuc_cost_usd
```

```{r}
tsbl_nuc_cost_usd %>%
  filter(YEAR == 2023)
```


```{r}
# proportion of TAF

cost_taf_2023 <- tsbl_nuc_cost_usd %>% filter(YEAR == 2023 & NUC == "TAF") %>% pull(SUM) 

cost_total_2023 <- tsbl_nuc_cost_usd %>% filter(YEAR == 2023 & NUC == "Total") %>% pull(SUM) 

print(cost_total_2023)

print(cost_taf_2023/cost_total_2023 *100)
```

```{r}
tsbl_nuc_cost_usd %>% filter(NUC == "ETV (generic)") %>%
  as_tibble() %>%
  filter(SUM == min(SUM))
```

```{r}
tsbl_nuc_cost_usd %>% filter(NUC == "ETV (generic)") %>%
  as_tibble() %>%
  filter(SUM == max(SUM))
```


```{r}
tsbl_nuc_cost_usd %>% filter(NUC == "ETV (generic)") %>%
  as_tibble() %>%
  summarise(MIN = min(SUM),
            MAX = max(SUM),
            MIN_usd = min(SUM_usd_m),
            MAX_usd = max(SUM_usd_m))
```

```{r}
tsbl_nuc_cost_usd %>%
  filter(NUC == "TDF") 
```


```{r}
tsbl_nuc_cost_usd %>%
  filter(NUC == "TDF") %>%
    as_tibble() %>%
  ungroup() %>%
  filter(SUM == max(SUM))
```


```{r}
tsbl_nuc_cost %>%
  as_tibble() %>%
  filter(NUC != "Total") %>%
  group_by(YEAR) %>%
  mutate(TOTAL = sum(SUM)) %>%
  ungroup() %>%
  mutate(PCT = SUM/TOTAL * 100) %>%
  filter(YEAR == 2023)
```




```{r}
label_nuc_cost <- tsbl_nuc_cost %>%
  filter(NUC %in% c("TDF", "TAF") & YEAR>= 2017) %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
   mutate(p_label = case_when(p_value <= 0.001 ~ "*p* < 0.001",
                             .default = paste0("*p* = ", as.character(round(p_value, 5))))) %>%
  mutate(adj_r_label = round(adj_r_squared, 2)) %>%
  mutate(adj_r_label = as.character(adj_r_label)) %>%
  mutate(adj_r_label = case_when(str_length(adj_r_label) == 3 ~ str_c(adj_r_label, "0"),
                               .default = adj_r_label))

label_nuc_cost
```


```{r}
lm_nuc_cost <- tsbl_nuc_cost %>%
  filter(NUC %in% c("TDF", "TAF") & YEAR>= 2017) %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR") %>%
  left_join(label_nuc_cost %>% select(NUC, df.residual),
            by = join_by(NUC)) %>%
  mutate(ci_low = estimate + std.error * qt(0.025, df= df.residual),
         ci_up = estimate + std.error * qt(1-0.025, df = df.residual)) %>%
  mutate(ci_low_label = round(ci_low, digits = 2),
         ci_up_label = round(ci_up, digits = 2)) %>%
  mutate(lm_label = round(estimate, digits = 2)) %>%
  mutate(lm_label = paste0(lm_label, " [",
                           ci_low_label, ", ",
                           ci_up_label, "]"))

lm_nuc_cost
```

```{r}
label_nuc_cost <- label_nuc_cost %>%
  left_join(lm_nuc_cost %>% select(NUC, lm_label), by = join_by(NUC)) %>%
  mutate(label = str_c("β<sub>1</sub> = ", lm_label,"<br>",
                       p_label, "<br>", "*R*<sup>2</sup><sub>adj</sub> = ", adj_r_label)) 
```


```{r}
fit_nuc_cost <- tsbl_nuc_cost %>%
  filter(NUC %in% c("TAF") & YEAR>= 2017) %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR))%>%
  augment()

fit_nuc_cost 
```



```{r}
p1_a1 <- tsbl_nuc_cost %>%
  mutate(SUM = if_else(NUC == "ETV (total)", NA, SUM)) %>%
  ggplot(aes(YEAR, SUM, group = NUC, colour = NUC))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  geom_line(data = fit_nuc_cost,
            aes(YEAR, .fitted, group = NUC),
            colour = "#7f7f7f",
            linewidth = 0.3, alpha = 0.8)+
    scale_colour_manual(values = c("black",
                                   "#e377c2",
                                 "#8c564b",
                                 "#2ca02c",
                                 "#1f77b4",
                                 "#17becf",
                                 "#ff7f0e",
                                 "#d62728"),
                      name = "NA")+
  geom_richtext(data = label_nuc_cost %>% filter(NUC == "TAF") %>%
                  mutate(label = str_remove(label, "\\s\\[[^\\]]+\\]")),
                aes(x = 2019, y = 21, label = label),
                hjust = 0, vjust = 0.5, size = 2.8,
                fill = NA, label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt"),
                inherit.aes = FALSE) +
    geom_text(data = tsbl_nuc_cost %>% filter(YEAR == 2016 & NUC == "Total"),
             aes(x = 2016, y = SUM-40/15, label = round(SUM, digits = 1)),
             size = 2.8, colour = "black",
             vjust = 0, 
              inherit.aes = FALSE)+
   geom_text(data = tsbl_nuc_cost %>% filter(YEAR == 2016 & NUC == "ETV (branded)"),
              aes(x = 2016, y = SUM + 40/20, label = round(SUM, digits = 1)),
              size = 2.8, colour = "black",
              vjust = 0.5,
              inherit.aes = FALSE)+
  geom_text(data = tsbl_nuc_cost %>% filter(YEAR == 2017 & NUC == "TDF"),
              aes(x = 2017, y = SUM + 40/20, label = round(SUM, digits = 2)),
              size = 2.8, colour = "black",
              vjust = 0.5,
              inherit.aes = FALSE)+
  geom_text(data = tsbl_nuc_cost %>% filter(YEAR == 2023 & NUC == "Total"),
             aes(x = 2023, y = SUM + 40/20, label = round(SUM, digits = 1)),
             size = 2.8, colour = "black",
             vjust = 0.5,
              inherit.aes = FALSE)+
    geom_text(data = tsbl_nuc_cost %>% filter(YEAR == 2023 & NUC == "TAF"),
              aes(x = 2023, y = SUM - 40/20, label = round(SUM, digits = 1)),
              size = 2.8, colour = "black",
              vjust = 0.5,
              inherit.aes = FALSE)+
    geom_text(data = tsbl_nuc_cost %>% filter(YEAR %in% c(2019, 2023) & NUC == "ETV (generic)"),
              aes(x = YEAR, y = SUM + 40/20, label = round(SUM, digits = 2)),
              size = 2.8, colour = "black",
              vjust = 0.5,
              inherit.aes = FALSE)+
        geom_text(data = tsbl_nuc_cost %>% filter(YEAR == 2023 & NUC == "ETV (branded)"),
              aes(x = 2023, y = SUM + 40/20, label = round(SUM, digits = 2)),
              size = 2.8, colour = "black",
              vjust = 0.5,
              inherit.aes = FALSE)+
  
  
  scale_y_continuous(
                     breaks = c(seq(0, 40, 10)),
                     limits = c(0, 40),
                     label = label_comma()) +
  coord_cartesian(clip = "off")+
  guides(colour = guide_legend(nrow = 1))+
  labs(tag = "a",
       x = "Year",
       y = "**Cost (10<sup>9</sup> JPY)**")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold",
                                    margin = margin(0, 0, 0, 0, "mm")),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0),
        legend.location = "plot",
        legend.position = "bottom",
        legend.justification = c(0, 0.5),
        legend.margin = margin(0,0,0,0, "mm"),
        legend.box.margin = margin(0,0,0,0, "mm"),
        legend.box.spacing = unit(0, "mm"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,5,0,0, "mm"))

p1_a1
```


# df_nuc_dem

```{r}
tsbl_nuc_dem <- df_nuc_dem %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR, NUC) %>%
  summarise(SUM = sum(TOTAL)) %>%
  bind_rows(df_nuc_dem_etv) %>%
  mutate(SUM = case_when( YEAR %in% c("2015", "2019", "2023") ~ SUM/366,
                          .default = SUM/365)) %>%
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "ETV (total)",
                                      "TDF",
                                      "TAF"))) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  ungroup() %>%
  as_tsibble(index = YEAR, key = NUC)
```

```{r}
tsbl_nuc_dem
```


```{r}
label_nuc_dem <- tsbl_nuc_dem %>%
  filter(NUC %in% c("ETV (total)", "TDF", "TAF") & YEAR>= 2017) %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
   mutate(p_label = case_when(p_value <= 0.001 ~ "*p* < 0.001",
                             .default = paste0("*p* = ", as.character(round(p_value, 3))))) %>%
  mutate(adj_r_label = round(adj_r_squared, 2)) %>%
  mutate(adj_r_label = as.character(adj_r_label)) %>%
  mutate(adj_r_label = case_when(str_length(adj_r_label) == 3 ~ str_c(adj_r_label, "0"),
                               .default = adj_r_label))

label_nuc_dem
```


```{r}
lm_nuc_dem <- tsbl_nuc_dem %>%
  filter(NUC %in% c("ETV (total)", "TDF", "TAF") & YEAR>= 2017) %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR") %>%
  left_join(label_nuc_dem %>% select(NUC, df.residual),
            by = join_by(NUC)) %>%
    mutate(ci_low = estimate + std.error * qt(0.025, df = df.residual),
         ci_up = estimate + std.error * qt(1-0.025, df = df.residual)) %>%
  mutate(ci_low_label = round(ci_low, digits = 0),
         ci_up_label = round(ci_up, digits = 0)) %>%
  mutate(lm_label = round(estimate, digits = 0)) %>%
  mutate(across(c(ci_low_label,ci_up_label, lm_label), ~ scales::comma(.x))) %>%
  mutate(lm_label = paste0(lm_label, " [",
                           ci_low_label, ", ",
                           ci_up_label, "]")) 

lm_nuc_dem 
```


```{r}
label_nuc_dem <-label_nuc_dem %>%
  left_join(lm_nuc_dem %>% select(NUC, lm_label),
            by = join_by(NUC)) %>%
  mutate(label = str_c("β<sub>1</sub> = ", lm_label, "<br>",
                       p_label, "<br>", "*R*<sup>2</sup><sub>adj</sub> = ", adj_r_label)) 

lm_nuc_dem 
```


```{r}
fit_nuc_dem <- tsbl_nuc_dem %>%
  filter(NUC %in% c("ETV (total)", "TAF") & YEAR>= 2017) %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR))%>%
  augment()

fit_nuc_dem 
```


```{r}
# add annotations

p1_a2 <- tsbl_nuc_dem %>%
  filter(NUC != "ADF") %>%
  ggplot(aes(YEAR, SUM, group = NUC, colour = NUC)) +
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  geom_line(data = fit_nuc_dem,
            aes(YEAR, .fitted, group = NUC), colour = "#7f7f7f",
            alpha =  0.8,
            linewidth = 0.3,
            inherit.aes = FALSE)+
  scale_colour_manual(values = c("#e377c2",
                                # "#8c564b",
                                 "#2ca02c",
                                 "#1f77b4",
                                 "#17becf",
                                 "#ff7f0e",
                                 "#d62728"),
                      name = "NA")+
  geom_richtext(data = label_nuc_dem %>% filter(NUC == "ETV (total)") %>%
                  mutate(label = str_remove(label, "\\s\\[[^\\]]+\\]")),
                aes(x = 2019, y = 90000, label = label),
                hjust = 0, vjust = 0.5, size = 2.8,
                fill = NA, label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt"),
                inherit.aes = FALSE) +
   geom_richtext(data = label_nuc_dem %>% filter(NUC == "TAF") %>%
                  mutate(label = str_remove(label, "\\s\\[[^\\]]+\\]")),
                aes(x = 2019, y = 57000, label = label),
                hjust = 0, vjust = 0.5, size = 2.8,
                 fill = NA, label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt"),
                inherit.aes = FALSE) +
     geom_text(data = tsbl_nuc_dem %>% filter(YEAR == 2016 & NUC == "ETV (branded)"),
             aes(x = 2016, y = SUM + 100000/20, label = scales::comma(round(SUM))),
             size = 2.8, colour = "black",
             hjust = 1,
             vjust = 0.5,
              inherit.aes = FALSE)+
   geom_text(data = tsbl_nuc_dem %>% filter(YEAR %in% c(2017, 2023) & NUC == "ETV (total)"),
             aes(x = YEAR, y = SUM + 100000/20, label = scales::comma(round(SUM))),
             size = 2.8, colour = "black",
             vjust = 0.5,
              inherit.aes = FALSE)+
    geom_text(data = tsbl_nuc_dem %>% filter(YEAR == 2023 & NUC == "TAF"),
              aes(x = 2023, y = SUM - 100000/20, label = scales::comma(round(SUM))),
              size = 2.8, colour = "black",
              vjust = 0.5,
              inherit.aes = FALSE)+
    geom_text(data = tsbl_nuc_dem %>% filter(YEAR == 2023 & NUC == "ETV (generic)"),
              aes(x = 2023, y = SUM - 100000/20, label = scales::comma(round(SUM))),
              size = 2.8, colour = "black",
              vjust = 0.5,
              inherit.aes = FALSE)+
        geom_text(data = tsbl_nuc_dem %>% filter(YEAR == 2023 & NUC == "ETV (branded)"),
              aes(x = 2023, y = SUM - 100000/20, label = scales::comma(round(SUM))),
              size = 2.8, colour = "black",
              vjust = 0.5,
              inherit.aes = FALSE)+
  
  scale_y_continuous(
                     breaks = c(seq(0, 100000, 20000)),
                     limits = c(0, 100000),
                     label = label_comma()) +
  coord_cartesian(clip = "off")+
  labs(#tag = "b",
       x = "Year",
       y = "People on NAs (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold",
                                    margin = margin(0, 0, 0, 0, "mm")),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,5 ,0,0, "mm"))

p1_a2
```

```{r}
# create dummy legend

levels_nuc_leg <- tsbl_nuc_dem %>%
  arrange(NUC) %>%
  distinct(NUC) %>%
  mutate(NUC = str_replace(NUC, "\\s", "\n")) %>%
  pull(NUC)
  

p1_a_dum <- tsbl_nuc_dem %>%
  as_tibble() %>%
  mutate(NUC = str_replace(NUC, "\\s", "\n")) %>%
  mutate(NUC = factor(NUC, levels = levels_nuc_leg)) %>%
  ggplot(aes(YEAR, SUM, group = NUC, colour = NUC)) +
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  geom_line(data = fit_nuc_dem,
            aes(YEAR, .fitted, group = NUC), colour = "#7f7f7f",
            alpha =  0.8,
            linewidth = 0.3,
            inherit.aes = FALSE)+
  scale_colour_manual(values = c("#e377c2",
                                 "#8c564b",
                                 "#2ca02c",
                                 "#1f77b4",
                                 "#17becf",
                                 "#ff7f0e",
                                 "#d62728"),
                      name = "NA")+
  
  scale_y_continuous(
                     breaks = c(seq(0, 100000, 20000)),
                     limits = c(0, 100000),
                     label = label_comma()) +
  guides(color = guide_legend(nrow = 1))+
  coord_cartesian(clip = "off")+
  labs(tag = "b",
       x = "Year",
       y = "People on NAs (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
       axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "bottom",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,5 ,0,0, "mm"),
        legend.margin = margin(0, 0, 0, 0, "mm"),
        legend.box.margin = margin(0, 0, 0, 0, "mm")
        )

p1_a_dum
```

```{r}
p1_a_leg <- p1_a_dum %>% get_legend() %>% wrap_elements()
```



```{r}
tsbl_nuc_dem %>%
  as_tibble() %>%
  filter(!NUC %in% c("ADF", "ETV (total)")) %>%
  group_by(YEAR) %>%
  mutate(TOTAL = sum(SUM)) %>%
  ungroup() %>%
  mutate(PCT = SUM/TOTAL * 100) %>%
  filter(YEAR == 2022) 
```

```{r}
tsbl_nuc_dem %>%
  as_tibble() %>%
  filter(!NUC %in% c("ADF", "ETV (total)")) %>%
  group_by(YEAR) %>%
  mutate(TOTAL = sum(SUM)) %>%
  ungroup() %>%
  mutate(PCT = SUM/TOTAL * 100) %>%
  filter(YEAR == 2022 & str_detect(NUC, "ETV")) %>%
  summarise(PCT = sum(PCT))
```


```{r}
# only 2022 ignore LAM ADF

df_nuc_dem %>%
  distinct(YEAR, COST_code, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR, NUC) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(SUM = SUM/365) %>%
  filter(NUC %in% c("LAM", "ADF"))
```

```{r}
tsbl_nuc_dem %>% 
  filter(YEAR == 2023)
```


```{r}
tsbl_nuc_dem_all <- df_nuc_dem %>%
  distinct(YEAR, DRUG_name, SHEET, .keep_all = TRUE) %>%
  group_by(YEAR, NUC) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(SUM = case_when( YEAR %in% c(2015, 2019, 2023) ~ SUM/366,
                          .default = SUM/365)) %>%
  filter(NUC != "ADF") %>%
  ungroup() %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(SUM)) %>%
  mutate(NUC = "NUC") %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(index = YEAR, key = NUC)
  

tsbl_nuc_dem_all
```

```{r}
label_nuc_dem_all <- tsbl_nuc_dem_all %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
   mutate(p_label = case_when(p_value <= 0.001 ~ "*p* < 0.001",
                             .default = paste0("*p* = ", as.character(round(p_value, 3))))) %>%
  mutate(adj_r_label = round(adj_r_squared, 2)) %>%
  mutate(adj_r_label = as.character(adj_r_label)) %>%
  mutate(adj_r_label = case_when(str_length(adj_r_label) == 3 ~ str_c(adj_r_label, "0"),
                               .default = adj_r_label))

label_nuc_dem_all
```

```{r}
lm_nuc_dem_all <- tsbl_nuc_dem_all %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  left_join(label_nuc_dem_all %>% select(NUC, df.residual),
            by = join_by(NUC)) %>%
  mutate(term = str_remove_all(term, "\\(|\\)")) %>%
  mutate(term = str_to_lower(term)) %>%
  mutate(est = round(estimate, digits = 0)) %>%
  mutate(ci_low = estimate + std.error * qt(0.025, df.residual),
         ci_up = estimate + std.error * qt(1-0.025, df.residual)) %>%
  mutate(ci_low_label = round(ci_low, digits = 0),
         ci_up_label = round(ci_up, digits = 0)) %>%
  mutate(across(c(est, ci_low_label, ci_up_label), ~ scales::comma(.x))) %>%
  filter(term == "year") %>%
  mutate(lm = paste0("β<sub>1</sub> = ", est, 
                     " [", ci_low_label,
                     ", ", ci_up_label, "]")) 
 

lm_nuc_dem_all
```


```{r}
label_nuc_dem_all <- label_nuc_dem_all %>%
  left_join(lm_nuc_dem_all, by = join_by(NUC)) %>%
  mutate(label = str_c(lm, "<br>",
                       p_label, "<br>", "*R*<sup>2</sup><sub>adj</sub> = ", adj_r_label)) 
```

```{r}
# exploatory remove adefovir

p1_b1 <- tsbl_nuc_dem_all %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  augment() %>%
  ggplot()+
  geom_point(aes(YEAR, SUM), size = 1, colour = "black")+
  geom_line(aes(YEAR, SUM, group = NUC), 
            linewidth = 0.3, colour = "black")+
  geom_line(aes(YEAR, .fitted, group = NUC), 
            linewidth = 0.3, colour = "#7f7f7f", alpha = 0.8)+
  geom_richtext(data = label_nuc_dem_all %>%
                  mutate(label = str_remove(label, "\\s\\[[^\\]]+\\]")),
                aes(x = 2017, y = 0, label = label),
                hjust = 0, vjust = 0, size = 2.8,
                fill = NA, label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt"),
                inherit.aes = FALSE) +
  geom_richtext(data = tsbl_nuc_dem_all %>% filter(YEAR %in%c(2014)) %>% mutate(label = scales::comma(round(SUM))),
                aes(x = YEAR, y = SUM - 150000/15, label = label),
                hjust = 0, vjust = 0.5, size = 2.8,
                fill = NA, label.color = NA,
                inherit.aes = FALSE) +
  geom_richtext(data = tsbl_nuc_dem_all %>% filter(YEAR %in%c(2015, 2023)) %>% mutate(label = scales::comma(round(SUM))),
                aes(x = YEAR, y = SUM + 150000/15, label = label),
                hjust = 0.5, vjust = 0.5, size = 2.8,
                fill = NA, label.color = NA,
                inherit.aes = FALSE) +

  scale_y_continuous(
                     breaks = c(seq(0, 150000, 50000)),
                     limits = c(0, 150000),
                     label = label_comma()) +
  coord_cartesian(clip = "off")+
  labs(tag = "b",
       x = "Year",
       y = "People on NAs (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold",
                                    margin = margin(0, 0, 0, 0, "mm")),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,5,0,0, "mm"))

p1_b1
```



```{r}
tsbl_nuc_dem_pct <- tsbl_nuc_dem_all %>%
  left_join(df_pop_dem %>% 
              filter(AGE== "total") %>%
              mutate(YEAR = as.numeric(YEAR)),
            by = join_by(YEAR)) %>%
  mutate(PCT = SUM/ (ALL_total * 1000) * 100)

tsbl_nuc_dem_pct
```

```{r}
tsbl_nuc_dem_pct %>%
  group_by_key() %>%
  model(tslm = TSLM(PCT ~ YEAR)) %>%
  tidy() 
  
```


```{r}
label_nuc_dem_pct <- tsbl_nuc_dem_pct %>%
  group_by_key() %>%
  model(tslm = TSLM(PCT ~ YEAR)) %>%
  glance() %>%
   mutate(p_label = case_when(p_value <= 0.001 ~ "*p* < 0.001",
                             .default = paste0("*p* = ", as.character(round(p_value, 3))))) %>%
  mutate(adj_r_label = round(adj_r_squared, 2)) %>%
  mutate(adj_r_label = as.character(adj_r_label)) %>%
  mutate(adj_r_label = case_when(str_length(adj_r_label) == 3 ~ str_c(adj_r_label, "0"),
                               .default = adj_r_label))

label_nuc_dem_pct
```

```{r}
lm_nuc_dem_pct <- tsbl_nuc_dem_pct %>%
  group_by_key() %>%
  model(tslm = TSLM(PCT ~ YEAR)) %>%
  tidy() %>%
  left_join(label_nuc_dem_pct %>% select(NUC, df.residual),
            by = join_by(NUC)) %>%
  mutate(term = str_remove_all(term, "\\(|\\)")) %>%
  mutate(term = str_to_lower(term)) %>%
  mutate(est = round(estimate, digits = 4)) %>%
  mutate(ci_low = estimate + std.error * qt(0.025, df = df.residual),
         ci_up = estimate + std.error * qt(1-0.025, df = df.residual)) %>%
  mutate(ci_low_label = round(ci_low, digits = 4),
         ci_up_label = round(ci_up, digits = 4)) %>%
  filter(term == "year") %>%
  mutate(lm = paste0("β<sub>1</sub> = ", est, 
                     " [", ci_low_label,
                     ", ", ci_up_label, "]")) 

lm_nuc_dem_pct
```

```{r}
label_nuc_dem_pct <- label_nuc_dem_pct %>%
  left_join(lm_nuc_dem_pct,
            by = join_by(NUC)) %>%
  mutate(label = str_c(lm, "<br>",
                       p_label, "<br>", "*R*<sup>2</sup><sub>adj</sub> = ", adj_r_label)) 

label_nuc_dem_pct
```


```{r}
p1_b2 <- tsbl_nuc_dem_pct %>%
  group_by_key() %>%
  model(tslm = TSLM(PCT ~ YEAR)) %>%
  augment() %>%
  ggplot()+
  geom_point(aes(YEAR, PCT), size = 1, colour = "black")+
  geom_line(aes(YEAR, PCT, group = NUC),
            linewidth = 0.3, colour = "black")+
  geom_line(aes(YEAR, .fitted, group = NUC),
            linewidth = 0.3, colour = "#7f7f7f", alpha = 0.8)+
  geom_richtext(data = label_nuc_dem_pct %>%
                  mutate(label = str_remove(label, "\\s\\[[^\\]]+\\]")),
                aes(x = 2017, y = 0, label = label),
                hjust = 0, vjust = 0, size = 2.8,
                fill = NA, label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt"),
                inherit.aes = FALSE) +
   geom_richtext(data = tsbl_nuc_dem_pct %>% filter(YEAR %in% c(2014)) %>% mutate(label = round(PCT, 3)),
                aes(x = YEAR, y = PCT - 0.12/15 , label = label),
                hjust = 0, vjust = 0.5, size = 2.8,
                fill = NA, label.color = NA,
                inherit.aes = FALSE) +
     geom_richtext(data = tsbl_nuc_dem_pct %>% filter(YEAR %in% c(2015)) %>% mutate(label = round(PCT, 3)),
                aes(x = YEAR, y = PCT + 0.12/15 , label = label),
                hjust = 0.5, vjust = 0.5, size = 2.8,
                fill = NA, label.color = NA,
                inherit.aes = FALSE) +
    geom_richtext(data = tsbl_nuc_dem_pct %>% filter(YEAR %in% c(2023)) %>% mutate(label = round(PCT, 3)),
                aes(x = YEAR, y = PCT + 0.12/15 , label = label),
                hjust = 0.5, vjust = 0.5, size = 2.8,
                fill = NA, label.color = NA,
                inherit.aes = FALSE) +

  scale_y_continuous(
                     breaks = c(seq(0, 0.12, 0.02)),
                     limits = c(0, 0.12),
                     label = label_comma()) +
  coord_cartesian(clip = "off")+
  labs(#tag = "b",
       x = "Year",
       y = "Prevalence (%)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold",
                                    margin = margin(0, 0, 0, 0, "mm")),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,5,0,0, "mm"))

p1_b2
```

```{r}
saveRDS(p1_a1, "../plot/p1_a1.RDS")

saveRDS(p1_a2, "../plot/p1_a2.RDS")

saveRDS(p1_b1, "../plot/p1_b1.RDS")

saveRDS(p1_b2, "../plot/p1_b2.RDS")

#saveRDS(p1_a_leg, "../plot/p1_a_leg.RDS")
```
