---
title: "HBV NA"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)


library(ggh4x)

library(ggtext)
library(ggrepel)
library(glue)
library(scales)

library(fpp3)

library(sf)

library(patchwork)
library(broom)

library(mapdata)

```

```{r}
df_nuc_dem <- readRDS("../df/nuc/format/df_nuc_dem")
```

```{r}
df_nuc_prf <- readRDS("../df/nuc/format/df_nuc_prf")
```

```{r}
df_pop_prf <- readRDS("../rds/pop/prf/df_pop_prf")
```


```{r}
df_nuc_prf %>% filter(is.na(VALUE)) %>% View()
```


```{r}
# add region

df_nuc_prf <- df_nuc_prf %>%
  rename(YEAR = "YEAR_str") 
```

# make data frame for region

```{r}
# define region

hokkaido <- c("JP-01")

tohoku <- c(paste0("JP-0", as.character(2:7)))

kanto <- c(paste0("JP-0", as.character(8:9)), 
           paste0("JP-", as.character(10:14)))

chubu <- c(paste0("JP-", as.character(15:24)))

kinki <- c(paste0("JP-", as.character(25:30)))

chugoku <- c(paste0("JP-", as.character(31:35)))

shikoku <- c(paste0("JP-", as.character(36:39)))

kyushu_okinawa <- c(paste0("JP-", as.character(40:47)))

```


```{r}
levels_reg <- c("Hokkaido",
                "Tohoku",
                "Kanto",
                "Chubu",
                "Kansai",
                "Chugoku",
                "Shikoku",
                "Kyushu\nOkinawa")
```

```{r}
levels_prf <- df_nuc_prf %>%
  arrange(iso_3166_2) %>%
  distinct(PRF) %>%
  pull(PRF)
```


```{r}
df_nuc_prf  <- df_nuc_prf  %>%
  mutate(REG = case_when(iso_3166_2 %in% hokkaido ~ "Hokkaido",
                         iso_3166_2 %in% tohoku ~ "Tohoku",
                         iso_3166_2 %in% kanto ~ "Kanto",
                         iso_3166_2 %in% chubu ~ "Chubu",
                         iso_3166_2 %in% kinki ~ "Kansai",
                         iso_3166_2 %in% chugoku ~ "Chugoku",
                         iso_3166_2 %in% shikoku ~ "Shikoku",
                         iso_3166_2 %in% kyushu_okinawa ~ "Kyushu\nOkinawa")) %>%
  mutate(REG = factor(REG, levels = levels_reg)) %>%
  mutate(PRF = factor(PRF, levels = levels_prf))
```

# make map

```{r}
map_jp <-  maps::map("japan", 
                       plot = FALSE,
                       fill = TRUE) %>%
  st_as_sf() %>%
  rename(PRF = "ID") %>%
  mutate(PRF = str_to_title(PRF))
```

```{r}
map_jp <- map_jp %>%
  left_join(df_nuc_prf %>% distinct(PRF, PRF_jp, iso_3166_2, REG),
            by = join_by(PRF)) %>%
  mutate(PRF = factor(PRF, levels = levels_prf))
```

# df_prop
```{r}
df_pop_prf <- df_pop_prf %>%
  left_join(df_nuc_prf  %>% distinct(iso_3166_2, PRF_jp, REG),
            by = join_by(PRF_jp))
```



# regional map

```{r}
# world map by region
p_reg <- map_jp %>%
  ggplot()+
  geom_sf(aes(fill = REG), alpha = 0.7)+
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                    name = "Region"
                               )+
   scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  guides(fill = guide_legend(override.aes = list(alpha = 1, size = 2, colour = NA))) +
  theme_void()+
  theme(legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p_reg
```


```{r}
df_nuc_prf_count <- df_nuc_prf %>%
  filter(NUC != "ADF") %>%
  group_by(YEAR, PRF, iso_3166_2) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(SUM = case_when(YEAR %in% c("2015", "2019", "2023") ~ SUM/366,
                         .default = SUM/365)) %>%
  ungroup() %>%
  arrange(iso_3166_2) %>%
  select(!PRF) %>%
  left_join(map_jp, join_by(iso_3166_2)) 

df_nuc_prf_count
```


```{r}
p1_a1 <- df_nuc_prf_count %>%
  filter(YEAR %in% c("2023")) %>%
  ggplot(aes(PRF, SUM, fill = REG))+
  geom_col(width = 0.7)+
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 15000, 5000),
                     limits = c(0, 15000),
                     labels  = label_comma())+
  coord_cartesian(clip = "off")+
  labs(tag = "a",
       x  = "Prefecture",
       y = "People on NAs\n(n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "mm"))

p1_a1
```

```{r}
p1_b1 <- map_jp %>%
  left_join(df_nuc_prf_count %>%
              filter(YEAR %in% c("2023")) %>% select(iso_3166_2, SUM),
            by = join_by(iso_3166_2)) %>%
  ggplot()+
  geom_sf(aes(fill = SUM))+
  scale_fill_gradient(low= "white", high = "#E64626", na.value = "#d9d9d9",
                      limits = c(0, 15000),
                     labels = label_comma()) +
  labs(fill = "People on NAs\n(n)")+
  guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  labs(tag = "b")+
  theme_void()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.justification = c(0, 0.5),
        legend.justification.inside = c(1.2, 0.5),
        legend.background = element_blank(),
        legend.key.width  = unit(0.75, "lines"),
        legend.key.height = unit(1.5, "lines"),
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_b1
```



```{r}
p1_c1 <- df_nuc_prf_count %>%
  group_by(YEAR, REG) %>%
  summarise(SUM = sum(SUM)) %>%
  filter(YEAR %in% c("2023") ) %>%
  ggplot(aes(REG, SUM, fill = REG)) +
  geom_col(width = 0.7) +
   scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 40000, 20000),
                     limits = c(0, 40000),
                     labels  = label_comma())+
  coord_cartesian(clip = "off")+
  labs(tag = "c",
       x = "Region",
       y = "People on NAs\n(n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "mm"))

p1_c1
```


# total each prefecture

```{r}
tsbl_nuc_prf_count <- df_nuc_prf_count %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(key = PRF, index = YEAR)
```


```{r}
tsbl_nuc_prf_count %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() 
```


```{r}
label_nuc_prf_count <- tsbl_nuc_prf_count  %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  glance() %>%
  mutate(adj_r_label = round(adj_r_squared, 2)) %>%
  mutate(adj_r_label = as.character(adj_r_label)) %>%
  mutate(adj_r_label = case_when(str_length(adj_r_label) == 3 ~ str_c(adj_r_label, "0"),
                               .default = adj_r_label))
```

```{r}
lm_nuc_prf_count <- tsbl_nuc_prf_count  %>%
  group_by_key() %>%
  model(tslm = TSLM(SUM ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR") %>%
  left_join(label_nuc_prf_count %>% select(PRF, df.residual),
            by  = join_by(PRF)) %>%
  mutate(p_label = case_when(p.value < 0.0001 ~ "<sup>****</sup>",
                             .default = NA)) %>%
  mutate(est = round(estimate, digits = 0)) %>%
  mutate(ci_low = estimate + std.error * qt(0.025, df = df.residual),
         ci_up = estimate + std.error * qt(1-0.025, df = df.residual)) %>%
  mutate(ci_low_label = round(ci_low, digits = 0),
         ci_up_label = round(ci_up, digits = 0)) %>%
  mutate(lm_label = paste0("β<sub>1</sub> = ", est, p_label))

lm_nuc_prf_count
```


```{r}
label_nuc_prf_count <- label_nuc_prf_count %>%
  left_join(lm_nuc_prf_count %>% select(PRF, lm_label),
            by = join_by(PRF)) %>%
  mutate(label = str_c(lm_label, "<br>", "*R*<sup>2</sup><sub>adj</sub> = ", adj_r_label)) 
```


```{r}
lm_nuc_prf_count %>%
  filter(estimate == max(estimate) | estimate == min(estimate))
```

```{r}
lm_nuc_prf_count %>%
  mutate(p = case_when(p.value < 0.0001 ~ "< 0.0001",
                             .default = NA)) %>%
  mutate(ci = paste0("[", ci_low_label, ", ", ci_up_label, "]")) %>%
  select(PRF, est, ci, p) %>%
  rename(Prefecture = "PRF",
         beta_1 = "est",
         Confidence_interval = ci,
         p_value = "p") %>%
  write.xlsx("../table/TableS5.xlsx")
```


```{r}
label_nuc_prf_count %>%
  filter( adj_r_squared == max(adj_r_squared) | adj_r_squared == min(adj_r_squared))
```


```{r}

label_nuc_prf_count_unscale <- label_nuc_prf_count  %>%
  mutate(x = 2014,
         y = 15000,
         hjust = 0,
         vjust = 1) %>%
  mutate(y = if_else(PRF %in% c("Hokkaido", "Tokyo", "Osaka"), 0, y)) %>%
  mutate(vjust = if_else(PRF %in% c("Hokkaido", "Tokyo", "Osaka"), 0, vjust))

label_nuc_prf_count_unscale
```


```{r}
p2_a <- tsbl_nuc_prf_count  %>%
  ggplot(aes(YEAR, SUM, group = PRF, colour = REG))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  scale_colour_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  facet_wrap2(vars(PRF),
              nrow = 8, ncol = 6,
              axes = "all", remove_labels = "all")+
  geom_richtext(data = label_nuc_prf_count_unscale,
                aes(x = x, y = y, label = label, hjust = hjust, vjust = vjust),
                size = 2.8, colour = "black",
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  labs(x = "Year",
       y = "People on NAs (n)")+
    scale_x_continuous(
                     breaks = seq(2014, 2022, 2),
                     limits = c(2014, 2023))+
  scale_y_continuous(
                     breaks = seq(0, 15000, 5000),
                     limits = c(0, 15000),
                     labels = label_comma())+
  coord_cartesian(clip = "off")+
  theme_classic()+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold",
                                  margin = margin(1, 0, 0, 1, unit = "mm")),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black", 
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.spacing.x = unit(2, "mm"),
        panel.spacing.y = unit(1, "mm"))

p2_a
```



```{r}
p2 <- p2_a +
  inset_element(p_reg + theme(legend.position = "none"),
                1-1/6, 0, 1, 1/7, on_top = FALSE,
                align_to = "full")

```


```{r}
ggsave("../figure/FigS3.svg", p2, width = 175, height = 235, unit = "mm")
```


```{r}

label_nuc_prf_count_scale <- label_nuc_prf_count  %>%
  mutate(x = 2014,
         y = 0,
         hjust = 0,
         vjust = 0) #%>%
#  mutate(y = if_else(PRF %in% c("Hokkaido", "Tokyo", "Osaka"), 0, y)) %>%
#  mutate(vjust = if_else(PRF %in% c("Hokkaido", "Tokyo", "Osaka"), 0, vjust))

label_nuc_prf_count_scale
```

```{r}
label_nuc_prf_count_scale %>%
  mutate(adj_r_squared = round(adj_r_squared, 3)) %>%
  summarise(MAX = max(adj_r_squared),
            MIN = min(adj_r_squared))
```


```{r}
#p3_a <- 
  tsbl_nuc_prf_count  %>%
  ggplot(aes(YEAR, SUM, group = PRF, colour = REG))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
#  geom_smooth(method = "lm", se = FALSE)+
  scale_colour_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  facet_wrap2(vars(PRF),
              nrow = 8, ncol = 6,
              axes = "all",
              remove_labels = "x",
              scales = "free_y")+
  geom_richtext(data = label_nuc_prf_count_scale,
                aes(x = x, y = y, label = label, hjust = hjust, vjust = vjust),
                size = 2.6, colour = "black",
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  labs(x = "Year",
       y = "People on NAs (n)")+
    scale_x_continuous(
                     breaks = seq(2014, 2022, 2),
                     limits = c(2014, 2023))+
 scale_y_continuous(
                     limits = c(0, NA),
                     labels = label_comma())+
  coord_cartesian(clip = "off")+
  theme_classic()+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none")

#p3_a
```

```{r}
#p3 <- p3_a + inset_element(p_reg + theme(legend.position = "none"),
#                1-1/6, 0, 1, 1/8, on_top = FALSE,
#                align_to = "full")
```


```{r}
#ggsave("../figure/Fig5.pdf", p3, width = 175, height = 235, unit = "mm")
```


```{r}
prf_jp <- tsbl_nuc_prf_count %>% distinct(PRF) %>% arrange(PRF) %>% pull(PRF)

prf_jp
```

```{r}
tsbl_nuc_prf_count %>%
  group_by(PRF) %>%
  slice_max(SUM, n = 1) %>%
  arrange(desc(SUM))
```

```{r}
tsbl_nuc_prf_count %>% filter(YEAR == 2014 & SUM == min(SUM))

tsbl_nuc_prf_count %>% filter(YEAR == 2014 & SUM == max(SUM))

tsbl_nuc_prf_count %>% filter(YEAR == 2022 & SUM == min(SUM))

tsbl_nuc_prf_count %>% filter(YEAR == 2022 & SUM == max(SUM))
```



```{r}
df_nuc_scales <- tsbl_nuc_prf_count %>%
  group_by(PRF) %>%
  slice_max(SUM, n = 1) %>%
  mutate(ymax = case_when(SUM <500 ~ 500,
                         SUM >= 500 & SUM < 1000 ~ 1000,
                         SUM >= 1000 & SUM < 1500 ~ 1500,
                         SUM >= 1500 & SUM < 2000 ~ 2000,
                         SUM >= 2000 & SUM < 3000 ~ 3000,
                         SUM >= 3000 & SUM < 4000 ~ 4000,
                         SUM >= 4000 & SUM < 5000 ~ 5000,
                         SUM >= 5000 & SUM < 6000 ~ 6000,
                         SUM >= 6000 & SUM < 8000 ~ 8000,
                         SUM >= 8000 & SUM < 10000 ~ 10000,
                         SUM >= 10000 & SUM < 12000 ~ 12000,
                         SUM >= 12000 & SUM < 15000 ~ 15000,
                         .default = NA
                         )) %>%
  ungroup()
```

```{r}
df_nuc_scales %>% count(ymax)
```


```{r}
df_nuc_scales <- df_nuc_scales %>%
  mutate(n = case_when(ymax %in% c(5000) ~ 5,
                       ymax %in% c(1500, 3000, 15000) ~ 3,
                       ymax %in% c(1000, 2000, 6000, 8000, 12000) ~ 4,
                       .default = NA)) %>%
  mutate(ymin = rep(0, 47))
```

```{r}
df_nuc_scales <- df_nuc_scales %>% 
  mutate(range = ymax/n)
```


```{r}
df_nuc_scales %>% count(ymax, n)
```



```{r}
df_nuc_scales_split <- split(df_nuc_scales, df_nuc_scales$PRF)
```

```{r}
nuc_scales <- lapply(df_nuc_scales_split, function(x) {
  scale_y_continuous(limits = c(x$ymin, x$ymax),
                     breaks = seq(0, x$ymax, x$range),
                     labels = label_comma())
})
```

```{r}
nuc_scales[[1]]
```


```{r}
p3_a <- tsbl_nuc_prf_count  %>%
  ggplot(aes(YEAR, SUM, group = PRF, colour = REG))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
#  geom_smooth(method = "lm", se = FALSE)+
  scale_colour_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  facet_wrap2(vars(PRF),
              nrow = 8, ncol = 6,
              axes = "all",
              remove_labels = "x",
              scales = "free_y")+
  geom_richtext(data = label_nuc_prf_count_scale,
                aes(x = x, y = y, label = label, hjust = hjust, vjust = vjust),
                size = 2.6, colour = "black",
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  labs(x = "Year",
       y = "People on NAs (n)")+
    scale_x_continuous(
                     breaks = seq(2014, 2022, 2),
                     limits = c(2014, 2023))+
  ggh4x::facetted_pos_scales(y = nuc_scales)+
  #coord_cartesian(clip = "off")+
  theme_classic()+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold",
                                  margin = margin(1, 0, 1, 0, unit = "mm")),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 7, angle = 90, hjust = 1, vjust = 0.5, colour = "black"),
        axis.text.y = element_text(size = 7, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.spacing.x = unit(1, "mm"),
        panel.spacing.y = unit(1, "mm"))

p3_a
```

```{r}
p3 <- p3_a + inset_element(p_reg + theme(legend.position = "none"),
                1-1/6, 0, 1, 1/7, on_top = FALSE,
                align_to = "full")
```


```{r}
ggsave("../figure/Fig5.pdf", p3, width = 175, height = 235, unit = "mm",
       device = cairo_pdf)
```




```{r}
# calculate national average

df_nuc_prf_pct_mean <- df_nuc_prf %>%
    filter(NUC != "ADF") %>%
  distinct(YEAR, SHEET, DRUG_name, .keep_all = TRUE) %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(TOTAL)) %>%
  mutate(SUM = case_when(YEAR %in% c("2015", "2019", "2023") ~ SUM/366,
                         .default = SUM/365)) %>%
  left_join(df_pop_prf %>% filter(PRF_jp == "total") %>% select(YEAR, ALL_total),
            by = join_by(YEAR)) %>%
  mutate(PCT_mean = SUM/(ALL_total * 1000) * 100)

df_nuc_prf_pct_mean
```


```{r}
tsbl_nuc_prf_pct <- df_nuc_prf %>%
    filter(NUC != "ADF") %>%
  group_by(YEAR, iso_3166_2) %>%
    summarise(SUM = sum(VALUE)) %>%
  mutate(SUM = case_when(YEAR %in% c("2015", "2019", "2023") ~ SUM/366,
                         .default = SUM/365)) %>%
  left_join(map_jp, join_by(iso_3166_2)) %>%
  mutate(ID = str_c(PRF_jp, "_", YEAR)) %>%
  left_join(df_pop_prf %>%
              mutate(ID = str_c(PRF_jp, "_", YEAR)) %>%
              select(ID, ALL_total),
            by = join_by(ID)) %>%
  mutate(PCT = SUM/(ALL_total*1000) * 100) %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  as_tsibble(index = YEAR, key = PRF)

tsbl_nuc_prf_pct 
```

```{r}
tsbl_nuc_prf_pct %>% filter(YEAR == 2014 & PCT == min(PCT))

tsbl_nuc_prf_pct %>% filter(YEAR == 2014 & PCT == max(PCT))

tsbl_nuc_prf_pct %>% filter(YEAR == 2022 & PCT == min(PCT))

tsbl_nuc_prf_pct %>% filter(YEAR == 2022 & PCT == max(PCT))

```


```{r}
tsbl_nuc_prf_pct %>%
  group_by_key() %>%
  model(tslm = TSLM(PCT ~ YEAR)) %>%
  glance() 
```






```{r}
label_nuc_prf_pct <- tsbl_nuc_prf_pct %>%
  group_by_key() %>%
  model(tslm = TSLM(PCT ~ YEAR)) %>%
  glance() %>%
  mutate(adj_r_label = round(adj_r_squared, 2)) %>%
  mutate(adj_r_label = as.character(adj_r_label)) %>%
  mutate(adj_r_label = case_when(str_length(adj_r_label) == 1 ~ str_c(adj_r_label, ".0"),
                                 str_length(adj_r_label) == 3 ~ str_c(adj_r_label, "0"),
                               .default = adj_r_label))

label_nuc_prf_pct
```




```{r}
lm_nuc_prf_pct <- tsbl_nuc_prf_pct %>%
  group_by_key() %>%
  model(tslm = TSLM(PCT ~ YEAR)) %>%
  tidy() %>%
  filter(term == "YEAR") %>%
  left_join(label_nuc_prf_pct %>% select(PRF, df.residual),
            by = join_by(PRF)) %>%
  mutate(p_label = case_when(p.value < 0.0001 ~ "<sup>****</sup>",
                             .default = NA)) %>%
  mutate(est = round(estimate, digits = 4)) %>%
  mutate(est = as.character(est)) %>%
  mutate(est = case_when(str_length(est) == 5 ~ paste0(est, "0"),
                         .default = est)) %>% 
  mutate(ci_low = estimate + std.error * qt(0.025, df = df.residual),
         ci_up = estimate + std.error * qt(1-0.025, df = df.residual)) %>%
  mutate(ci_low_label = round(ci_low, digits = 4),
         ci_up_label = round(ci_up, digits = 4)) %>%
  mutate(lm_label = paste0("β<sub>1</sub> = ", est, p_label))

lm_nuc_prf_pct 
```

```{r}
lm_nuc_prf_pct %>%
  filter(estimate == min(estimate) | estimate == max(estimate))
```

```{r}
label_nuc_prf_pct <- label_nuc_prf_pct %>%
  left_join(lm_nuc_prf_pct  %>% select(PRF, lm_label),
            by = join_by(PRF)) %>%
  mutate(label = str_c(lm_label, "<br>", "*R*<sup>2</sup><sub>adj</sub> = ", adj_r_label)) %>%
  mutate(x = 2014,
         y = 0.3,
         hjust = 0,
         vjust = 1) %>%
  mutate(y = if_else(PRF %in% c("Hokkaido", "Tottori"), 0, y)) %>%
  mutate(vjust = if_else(PRF %in% c("Hokkaido", "Tottori"), 0, vjust))
```


```{r}
lm_nuc_prf_pct %>% 
  mutate(p = case_when(p.value < 0.0001 ~ "< 0.0001",
                             .default = NA)) %>%
  mutate(ci_low_label = as.character(ci_low_label),
         ci_up_label = as.character(ci_up_label)) %>%
  mutate(ci_low_label = case_when(str_length(ci_low_label) == 5 ~ paste0(ci_low_label, "0"),
                                  .default = ci_low_label)) %>%
  mutate(ci_up_label = case_when(str_length(ci_up_label) == 5 ~ paste0(ci_up_label, "0"),
                                  .default = ci_up_label)) %>%
  mutate(ci = paste0("[", ci_low_label, ", ", ci_up_label, "]")) %>%
  select(PRF, est, ci, p) %>%
  rename(Prefecture = "PRF",
         beta_1 = "est",
         Confidence_interval = ci,
         p_value = "p") %>%
  write.xlsx("../table/TableS6.xlsx")
```


```{r}
label_nuc_prf_pct %>%
  filter(adj_r_squared == min(adj_r_squared) | adj_r_squared == max(adj_r_squared))
```


```{r}
label_nuc_prf_pct %>%
  mutate(adj_r_squared = round(adj_r_squared, 3)) %>%
  summarise(MIN = min(adj_r_squared),
            MAX = max(adj_r_squared))
```


```{r}
tsbl_nuc_prf_pct %>%
  group_by_key() %>%
  model(tslm = TSLM(PCT ~ YEAR)) %>%
  tidy()
```

# max prevalence

```{r}
tsbl_nuc_prf_pct %>%
  filter(YEAR == 2023) %>%
  filter(PCT == max(PCT))
```

```{r}
tsbl_nuc_prf_pct %>%
  filter(YEAR == 2023) %>%
  group_by(REG) %>%
  filter(PCT == max(PCT))
```


```{r}
p1_a2 <- tsbl_nuc_prf_pct %>%
  filter(YEAR == 2023) %>%
  ggplot(aes(PRF, PCT, fill = REG))+
  geom_col(width = 0.7)+
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 0.3, 0.1),
                     limits = c(0, 0.3))+
  geom_hline(yintercept = df_nuc_prf_pct_mean %>% filter(YEAR == "2023") %>% pull(PCT_mean),
             linetype = 2,
             linewidth = 0.3,
             colour = "black")+
  labs(
       x = "Prefecture",
       y = "Prevalence\n(%)")+
  theme_classic()+
   theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "mm"))

p1_a2
```

```{r}
p1_a <- p1_a1 + plot_spacer() + 
  p1_a2 +
  plot_layout(nrow = 3, ncol = 1,
              heights = c(1, 0.05, 1))

p1_a
```


```{r}
p1_b2 <- map_jp %>%
  left_join(tsbl_nuc_prf_pct %>%
              filter(YEAR %in% c("2023")) %>% select(iso_3166_2, PCT),
            by = join_by(iso_3166_2)) %>%
  ggplot()+
  geom_sf(aes(fill = PCT))+
  scale_fill_gradient(low= "white", high = "#E64626", na.value = "#d9d9d9",
                      limits = c(0, 0.3),
                      breaks = seq(0, 0.3, 0.1),
                      labels = label_comma()) +
  labs(fill = "Prevalence\n(%)")+
  guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  theme_void()+
 theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.justification = c(0, 0.5),
        legend.justification.inside = c(1.1, 0.5),
        legend.background = element_blank(),
        legend.key.width  = unit(0.75, "lines"),
        legend.key.height = unit(1.5, "lines"),
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))


p1_b2
```

```{r}
df_nuc_prf %>% head()
```

```{r}
df_pop_reg <- df_pop_prf %>%
  filter(!is.na(iso_3166_2)) %>%
  group_by(YEAR, REG) %>%
  summarise(ALL_total = sum(ALL_total)) %>%
  mutate(ID = str_c(REG, "_", YEAR)) %>%
  ungroup()

df_pop_reg
```

```{r}
df_nuc_prf_pct_reg <- df_nuc_prf %>%
    filter(NUC != "ADF") %>%
  group_by(YEAR, REG) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(SUM = case_when(YEAR %in% c("2015", "2019", "2023") ~ SUM/366,
                         .default = SUM/365)) %>%
  mutate(ID = str_c(REG, "_", YEAR)) %>%
  left_join(df_pop_reg %>% select(ID, ALL_total),
            by = join_by(ID)) %>%
  mutate(PCT = SUM/(ALL_total*1000) * 100) 

df_nuc_prf_pct_reg
```


```{r}
df_nuc_prf_pct_mean %>% filter(YEAR == "2023") %>% pull(PCT_mean)
```


```{r}
p1_c2 <- df_nuc_prf_pct_reg %>%
  filter(YEAR %in% c("2023") ) %>%
  ggplot(aes(REG, PCT, fill = REG)) +
  geom_col(width = 0.7) +
   scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 0.3, 0.1),
                     limits = c(0, 0.3),
                     labels  = label_comma())+
    geom_hline(yintercept = df_nuc_prf_pct_mean %>% filter(YEAR == "2023") %>% pull(PCT_mean),
             linetype = 2,
             linewidth = 0.3,
             colour = "black")+
  labs(
       x = "Region",
       y = "Prevalence\n(%)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "mm"))

p1_c2
```

```{r}
df_nuc_prf_pct_reg %>%
  filter(PCT == max(PCT)) %>%
  filter(YEAR == "2023")
```

```{r}
p1_c <- p1_c1 + plot_spacer()+
  p1_c2 +
  plot_layout(nrow = 3,
              heights = c(1, 0.05, 1))

p1_c
```
# correlation in 2023

```{r}
df_nuc_prf_2023 <- tsbl_nuc_prf_pct %>%
  filter(YEAR == "2023") %>%
  rename(POP = "ALL_total") %>% as_tibble()
```

```{r}
cor_2023 <- cor(df_nuc_prf_2023$POP, df_nuc_prf_2023$SUM, method = "pearson")

cor_2023 
```


```{r}
df_nuc_prf_2023_cor <- df_nuc_prf_2023 %>%
  ungroup() %>%
  mutate(POP = POP/1000) %>%
  select(SUM, POP) %>%
  nest() %>%
  mutate(
    fit = purrr::map(data, ~ cor.test(.x$POP, .x$SUM,
                                      method = "pearson")),
    tidied = purrr::map(fit, tidy),
    glanced = purrr::map(fit, glance)
  )
```

```{r}
df_nuc_prf_2023_cor %>% unnest(tidied)
```


# linear regression

```{r}
df_nuc_prf_2023_reg <-   df_nuc_prf_2023 %>%
  ungroup() %>%
  mutate(POP = POP/1000) %>%
  select(SUM, POP) %>%
  nest() %>%
  mutate(
    fit = purrr::map(data, ~ lm(SUM ~ POP, data = .x)),
    tidied = purrr::map(fit, tidy),
    glanced = purrr::map(fit, glance),
    augmented = purrr::map(fit, augment)
  )
```

```{r}
# tidy
df_nuc_prf_2023_reg_tidy <- df_nuc_prf_2023_reg %>% unnest(tidied)

df_nuc_prf_2023_reg_tidy
```

```{r}
df_nuc_prf_2023_reg_tidy %>% select(term, estimate) %>% 
  mutate(term = str_remove_all(term, "\\(|\\)")) %>%
              pivot_wider(names_from = term, values_from = estimate) 
```

```{r}
df_nuc_prf_2023_reg %>% unnest(glanced)
```


```{r}
df_reg_label <- df_nuc_prf_2023_reg %>% unnest(glanced) %>%
  mutate(term = "POP") %>%
  left_join(df_nuc_prf_2023_reg_tidy %>% 
              select(term, estimate) %>%
              mutate(term = str_remove_all(term, "\\(|\\)")) %>%
              pivot_wider(names_from = term, values_from = estimate) %>%
              mutate(term = "POP"),
            by = join_by(term)) %>%
  mutate(p_label = case_when(p.value <= 0.0001 ~ "*p* < 0.0001",
                             .default = as.character(round(p.value, 3)))) %>%
  mutate(adj_r_label = round(adj.r.squared, 2)) %>%
  mutate(adj_r_label = as.character(adj_r_label)) %>%
  mutate(adj_r_label = case_when(str_length(adj_r_label) == 3 ~ str_c(adj_r_label, "0"),
                               .default = adj_r_label)) %>%
  mutate(intercept_label = round(Intercept)) %>%
  mutate(slope_label = round(POP)) %>%
  mutate(label = paste0(
                        "*y* = ", slope_label, "*x*", " + ", intercept_label, "<br>",
                        p_label, "<br>",
                        "*R*<sup>2</sup><sub>adj</sub> = ",adj_r_label))
  

df_reg_label
```





```{r}
p1_d1 <- df_nuc_prf_2023 %>%
   mutate(POP = POP/1000) %>%
  mutate(label = PRF) %>%
  mutate(label = case_when(label %in% c("Tokyo",
                                        "Osaka",
                                        "Hokkaido",
                                        "Fukuoka",
                                        "Hyogo",
                                        "Kanagawa",
                                        "Aichi",
                                        "Saitama",
                                        "Chiba",
                                       # "Shizuoka",
                                        "Hiroshima") ~ label,
                           .default = NA)) %>%
  ggplot(aes(POP, SUM))+
   geom_point( aes(fill = REG), colour = "black", alpha = 0.7, shape = 21,
               size = 1.5)+
   scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                      name = "Region")+
 # scale_size_continuous(range = c(1.5, 4))+
  geom_richtext(data = df_reg_label ,
                aes(x = 0, y = 15000, label = label),
                size = 2.8,
                hjust = 0, vjust = 1,
                fill = NA, label.color = NA)+
    geom_line(stat= "smooth",
              method = "lm", 
              linewidth = 0.5,
              linetype = 1,
              alpha = 0.7,
              colour = "#17becf")+
    geom_text_repel(aes(label = label),
                  size = 2.6, 
                  segment.size = 0.3, segment.alpha = 0.5,
                  max.overlaps = Inf,
                  seed = 1)+
  scale_x_continuous(breaks = seq(0, 15, 5),
                     limits = c(0, 15))+
  scale_y_continuous(breaks = seq(0, 15000, 5000),
                     limits = c(0, 15000),
                     labels = label_comma())+
  coord_cartesian(clip = "off")+
  labs(tag = "d",
       x = "Population of prefecture (10<sup>6</sup>)",
       y = "People on NAs (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_d1
```

```{r}
p_reg <- p_reg + theme(legend.position = "none")

p_reg
```


```{r}
p1_d <- p1_d1 +
  inset_element(p_reg, 0.45, 0, 1, 0.8)

p1_d
```


```{r}
p1 <- patchwork::free(p1_a, side = "tblr") + 
  patchwork::free(p1_b1, side = "lr") +
  patchwork::free(p1_b2, side = "lr") +
  patchwork::free(p1_c, side = "trbl") + 
  patchwork::free(p1_d, side = "trbl") +
  plot_layout(design = "
              AAAAAAAAAAAAAA
              AAAAAAAAAAAAAA
              AAAAAAAAAAAAAA
              BBBBBBBCCCCCCC
              BBBBBBBCCCCCCC
              BBBBBBBCCCCCCC
              DDDDDDEEEEEEEE
              DDDDDDEEEEEEEE
              DDDDDDEEEEEEEE") 

p1
```

```{r}
ggsave("../figure/Fig7.pdf", p1, width = 175, height = 235, units = "mm")
```


```{r}
# unscaled PCT

p4_a <- tsbl_nuc_prf_pct %>%
  ggplot(aes(YEAR, PCT, group = PRF, colour = REG))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
#  geom_smooth(method = "lm", se = FALSE)+
  scale_colour_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  facet_wrap2(vars(PRF),
              nrow = 8, ncol = 6,
              axes = "all", remove_labels = "all")+
  geom_richtext(data = label_nuc_prf_pct,
                aes(x = x, y = y, label = label, hjust = hjust, vjust = vjust),
                size = 2.6, colour = "black",
                fill = NA, label.color = NA,
                inherit.aes = FALSE)+
  labs(x = "Year",
       y = "Prevalence (%)")+
    scale_x_continuous(
                     breaks = seq(2014, 2022, 2),
                     limits = c(2014, 2023))+
  scale_y_continuous(
                     breaks = seq(0, 0.3, 0.1),
                     limits = c(0, 0.3))+
  coord_cartesian(clip = "off")+
  theme_classic()+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold",
                                  margin = margin(1, 0, 1, 0)),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.spacing.x = unit(2, "mm"),
        panel.spacing.y = unit(1, "mm"))

p4_a
```


```{r}
# assemble p1_c 
p4 <- p4_a + 
  inset_element(p_reg + theme(legend.position = "none"),
                1-1/6, 0, 1, 1/7, on_top = FALSE,
                align_to = "full")

p4
```

```{r}
ggsave("../figure/Fig6.pdf", p4, width = 175, height = 235, units = "mm",
       device = cairo_pdf)
```

