---
title: "HBV NA"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(fpp3)

library(cowplot)
library(patchwork)
library(ggtext)
library(scales)

library(ggh4x)

library(viridis)
library(pals)
```

```{r}
# make df folder

dir.create("../df/figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/nuc/analysis", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_nuc_dem <- readRDS("../df/nuc/format/df_nuc_dem")
```

```{r}
df_nuc_prf <- readRDS("../df/nuc/format/df_nuc_prf")
```


```{r}
df_pop_dem <- readRDS("../rds/pop/dem/df_pop_dem")
```

# modify nuc_dem

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "TDF",
                                      "TAF"))) %>%
  rename(YEAR = "YEAR_str")
  
```



```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(AGE_ori = AGE) %>%
    mutate(AGE = fct_recode(AGE,
                          "0-19" = "0-4",
                          "0-19" = "5-9",
                          "0-19" = "10-14",
                          "0-19" = "15-19")) 
```

```{r}
levels_age <- df_nuc_dem %>%
  distinct(AGE, .keep_all = TRUE) %>%
  arrange(AGE) %>%
  pull(AGE)

levels_age 
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(AGE = factor(AGE, levels = levels_age))
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(SEX = case_when(SEX == "M" ~ "Male",
                         SEX == "F" ~ "Female")) %>%
  mutate(SEX = factor(SEX, levels = c("Male", "Female")))
```


# format prf

```{r}
df_nuc_prf <- df_nuc_prf %>%
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "TDF",
                                      "TAF"))) %>%
  rename(YEAR = "YEAR_str")
  
```

# check discrepancy

```{r}
cat_dem <- df_nuc_dem %>%
  mutate(ID = paste0(YEAR, "_", SHEET, "_", DRUG_name, "_")) %>%
  distinct(ID) %>%
  pull(ID)

cat_prf <- df_nuc_prf %>%
   mutate(ID = paste0(YEAR, "_", SHEET, "_", DRUG_name, "_")) %>%
  distinct(ID) %>%
  pull(ID)

setdiff(cat_dem, cat_prf)

setdiff(cat_prf, cat_dem)

# no results -> no descrepancy
```

# analysis

```{r}
# demogrpahics all NUC

df_nuc_dem %>%
  filter(NUC != "ADF") %>%
  group_by(AGE, SEX, YEAR) %>%
  summarise(SUM = sum(VALUE))
```


```{r}
df_nuc_dem_total <- df_nuc_dem %>%
  filter(NUC != "ADF") %>%
  distinct(SHEET, DRUG_name, YEAR, .keep_all = TRUE) %>%
  group_by(YEAR) %>%
  summarise(TOTAL = sum(TOTAL)/365) 

df_nuc_dem_total
```

```{r}
df_nuc_prf_total <- df_nuc_prf %>%
  filter(NUC != "ADF") %>%
  distinct(SHEET, DRUG_name, YEAR, .keep_all = TRUE) %>%
  group_by(YEAR) %>%
  summarise(TOTAL = sum(TOTAL)/365) 

df_nuc_prf_total
```

```{r}
df_nuc_dem_total %>%
  left_join(df_nuc_prf_total,
            by = join_by(YEAR),
            suffix = c("_dem", "_prf")) %>%
  mutate(MATCH = TOTAL_dem == TOTAL_prf)
```


```{r}
df_nuc_est_dem <-df_nuc_dem %>%
  filter(NUC != "ADF") %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(VALUE_dem = case_when(YEAR %in% c("2016", "2020") ~ SUM/366,
                               .default = SUM/366))

df_nuc_est_dem 
```


```{r}
df_nuc_est_prf <-df_nuc_prf %>%
  filter(NUC != "ADF") %>%
  group_by(YEAR) %>%
  summarise(SUM = sum(VALUE)) %>%
  mutate(VALUE_prf = case_when( YEAR %in% c("2016", "2020") ~ SUM/366,
                                .default = SUM/365)) 

df_nuc_est_prf
```


```{r}
df_nuc_est_diff <- df_nuc_dem_total %>%
  left_join(df_nuc_est_dem, by = join_by(YEAR)) %>%
  left_join(df_nuc_est_prf, by = join_by(YEAR)) %>%
  mutate(DIFF_dem = (VALUE_dem - TOTAL)/TOTAL *100) %>%
   mutate(DIFF_prf = (VALUE_prf - TOTAL)/TOTAL *100) 

df_nuc_est_diff
```

```{r}
df_nuc_est_diff %>%
  summarise(MAX_dem = max(DIFF_dem),
            MIN_dem = min(DIFF_dem),
            MAX_prf = max(DIFF_prf),
            MIN_prf = min(DIFF_prf))
  
```

```{r}
df_nuc_est_diff %>%
  select(YEAR, TOTAL, VALUE_dem, VALUE_prf, DIFF_dem, DIFF_prf) %>%
  mutate(across(c(TOTAL, starts_with("VALUE")), ~ round(.x, digits = 0))) %>%
  mutate(across(c(TOTAL, starts_with("VALUE")), ~ scales::comma(.x))) %>%
  mutate(across(c(TOTAL, starts_with("VALUE")), ~ format(.x, nsmall = 0))) %>%
  mutate(across(c(starts_with("DIFF")), ~ round(.x, digits = 3)))  %>%
  mutate(across(c(starts_with("DIFF")), ~ format(.x, nsmall = 3))) 
```



```{r}
df_nuc_est_diff %>%
  select(YEAR, TOTAL, VALUE_dem, VALUE_prf, DIFF_dem, DIFF_prf) %>%
  mutate(across(c(TOTAL, starts_with("VALUE")), ~ round(.x, digits = 0))) %>%
  mutate(across(c(TOTAL, starts_with("VALUE")), ~ scales::comma(.x))) %>%
  mutate(across(c(TOTAL, starts_with("VALUE")), ~ format(.x, nsmall = 0))) %>%
  mutate(across(c(starts_with("DIFF")), ~ round(.x, digits = 3)))  %>%
  mutate(across(c(starts_with("DIFF")), ~ format(.x, nsmall = 3))) %>%
  select(YEAR, TOTAL, VALUE_dem, DIFF_dem, VALUE_prf, DIFF_prf) %>%
  
  rename(Year = "YEAR",
         Total_estimate = "TOTAL",
         Demographic_estimate = "VALUE_dem",
         Prefecture_estimate = "VALUE_prf",
         Demographic_difference = "DIFF_dem",
         Prefecture_difference = "DIFF_prf") %>%
  
  write.xlsx("../table/TableS4.xlsx")
```



