---
title: "HBV NA"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(fpp3)

library(cowplot)
library(patchwork)
library(ggtext)
library(scales)

library(ggh4x)

library(viridis)
library(pals)
```

```{r}
# make df folder

dir.create("../df/figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/nuc/analysis", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_nuc_dem <- readRDS("../df/nuc/format/df_nuc_dem")
```

```{r}
df_cost_all <- readRDS("../rds/cost/df_cost_all")
```

```{r}
df_boj <- readRDS("../rds/boj/df_boj")
```

```{r}
df_pop_dem <- readRDS("../rds/pop/dem/df_pop_dem")
```

# modify nuc_dem

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(NUC = factor(NUC, levels = c("LAM",
                                      "ADF",
                                      "ETV (branded)",
                                      "ETV (generic)",
                                      "TDF",
                                      "TAF"))) %>%
  rename(YEAR = "YEAR_str")
  
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(AGE_ori = AGE) %>%
    mutate(AGE = fct_recode(AGE,
                          "0-19" = "0-4",
                          "0-19" = "5-9",
                          "0-19" = "10-14",
                          "0-19" = "15-19")) 
```

```{r}
levels_age <- df_nuc_dem %>%
  distinct(AGE, .keep_all = TRUE) %>%
  arrange(AGE) %>%
  pull(AGE)

levels_age 
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(AGE = factor(AGE, levels = levels_age))
```

```{r}
df_nuc_dem <- df_nuc_dem %>%
  mutate(SEX = case_when(SEX == "M" ~ "Male",
                         SEX == "F" ~ "Female")) %>%
  mutate(SEX = factor(SEX, levels = c("Male", "Female")))
```



# modify pop dem for each category

```{r}
df_pop_dem %>% count(YEAR)
```

```{r}
df_pop_dem %>% count(AGE)
```


```{r}
df_pop_dem_cat <- df_pop_dem %>%
  filter(AGE != "total") %>%
  mutate(AGE= str_remove(AGE, "_")) %>%
  mutate(AGE = as.numeric(AGE))
```


```{r}
df_pop_dem_cat <- df_pop_dem_cat %>%
  mutate(AGE_cat = case_when(AGE %in% 0:19 ~ "0-19",
                             AGE %in% 20:24 ~ "20-24",
                             AGE %in% 25:29 ~ "25-29",
                             AGE %in% 30:34 ~ "30-34",
                             AGE %in% 35:39 ~ "35-39",
                             AGE %in% 40:44 ~ "40-44",
                             AGE %in% 45:49 ~ "45-49",
                             AGE %in% 50:54 ~ "50-54",
                             AGE %in% 55:59 ~ "55-59",
                             AGE %in% 60:64 ~ "60-64",
                             AGE %in% 65:69 ~ "65-69",
                             AGE %in% 70:74 ~ "70-74",
                             AGE %in% 75:79 ~ "75-79",
                             AGE %in% 80:84 ~ "80-84",
                             AGE %in% 85:89 ~ "85-89",
                             AGE >= 90 ~ "90-"
                             ))
```

```{r}
df_pop_dem_cat %>% count(AGE_cat)
```


```{r}
df_pop_dem_cat %>% colnames()
```


```{r}
df_pop_dem_long <- df_pop_dem_cat %>%
  select(YEAR, AGE_cat, ALL_total, ALL_m, ALL_f) %>%
  rename(
         Male = "ALL_m",
         Female = "ALL_f") %>%
  pivot_longer(cols = c(Male, Female),
               names_to = "SEX",
               values_to = "POP") %>%
  mutate(SEX = factor(SEX, levels = c("Male", "Female")))
```

```{r}
df_pop_dem_long
```

# join pop data
```{r}
df_pop_dem_sa <- df_pop_dem_long %>%
  group_by(YEAR, AGE_cat, SEX) %>%
  summarise(POP = sum(POP)) %>%
  ungroup() %>%
  rename(AGE = "AGE_cat") %>%
  mutate(POP = POP/10^3)
```
```{r}
df_pop_dem_sa <- df_pop_dem_sa %>%
  bind_rows(df_pop_dem_sa %>%
              group_by(YEAR, AGE) %>%
              summarise(POP = sum(POP)) %>%
              mutate(SEX = "Total")
                          ) %>%
  mutate(SEX = factor(SEX, levels = c("Total", "Male", "Female")))
```




```{r}
df_pop_dem_sa %>%
  ggplot(aes(YEAR, POP, group = SEX, colour = SEX))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  scale_colour_manual(values = c("#7f7f7f", "#0072B2", "#D55E00"))+
  facet_wrap2(vars(AGE))+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
         strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold",
                                  margin = margin(0,0,0,0, "cm")),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        plot.margin = margin(0, 0, 0, 0, "mm"))
```


```{r}
df_pop_dem_sa %>%
  group_by(AGE) %>%
  slice_max(POP, n = 1) 
```


```{r}
df_pop_scales <- df_pop_dem_sa %>%
  as_tibble() %>%
  group_by(AGE) %>%
  slice_max(POP, n = 1) %>%
  mutate(ymax = case_when(POP < 5 ~ 5,
                          POP >5 & POP < 10  ~ 10,
                          POP > 10 & POP < 15  ~ 15,
                          POP > 15 & POP < 20  ~ 20,
                          POP > 20 & POP < 25  ~ 25,
                         .default = NA
                         )) %>%
  ungroup()
```

```{r}
df_pop_scales <- df_pop_scales %>%
  mutate(n = 5) %>%
  mutate(ymin = rep(0, 16)) 

df_pop_scales
```


```{r}
df_pop_scales <- df_pop_scales %>% 
  mutate(range = ymax/n)
```


```{r}
df_pop_scales %>% count(ymax, n)
```



```{r}
df_pop_scales_split <- split(df_pop_scales, df_pop_scales$AGE)

df_pop_scales_split
```

```{r}
nuc_pop_scales <- lapply(df_pop_scales_split, function(x) {
  scale_y_continuous(limits = c(x$ymin, x$ymax),
                     breaks = seq(0, x$ymax, x$range))
})
```

```{r}
p1 <- df_pop_dem_sa %>%
  mutate(YEAR = as.numeric(YEAR)) %>%
  ggplot(aes(YEAR, POP, group = SEX, colour = SEX))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  scale_colour_manual(values = c("#7f7f7f", "#1f77b4", "#d62728"),
                      name = "Sex")+
  facet_wrap2(vars(AGE),
              scales = "free_y",
              axes = "all",
              remove_labels = "x")+
  ggh4x::facetted_pos_scales(y = nuc_pop_scales)+
  labs(x = "Year",
       y = "**Population (10<sup>6</sup>)**")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
         strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold",
                                  margin = margin(0,0,0,0, "cm")),
        axis.title.x = element_text(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "bottom",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.key.height = unit(4, "mm"),
        plot.margin = margin(0, 0, 0, 0, "mm"),
        legend.margin = margin(0, 0, 0, 0, "mm"))

p1
```

```{r}
p1 <- p1 + plot_layout() &
  theme(legend.box.spacing = unit(3, "mm"))

ggsave("../figure/FigS1.svg", p1, width = 174, height = 120, units = "mm")
```

